### ISSUE TITLE
Handle multiple URL's in same call

### ISSUE THREAD

**Issue by pocketjoso** [pocketjoso/penthouse#10]
Penthouse should be able to create multiple `critical path css files` at the same time, from multiple passed in `URLs`. This way a user can essentially just list a number of pages (via URL's) in their build script, and every time they build, all their critical path css will be updated.

This will be a major version change, since it will change the core API.

#### What's needed

* The core script (`penthouse.js`) needs to be modified to execute the critical path css generating function once per passed in url, rather than just once. The script should also write the output to file(s), rather than just returning it. This leaves room for returning something else useful, perhaps something like how many bytes where saved, how many files where created, perhaps duration of execution. @pocketjoso will take care of this part.

* An option parser handling the multiple (possible) passed in URL's needs to be built into the penthouse ecosystem. It will also simplify the straight command line penthouse call by wrapping phantomjs and the config. @fatso83 is already on top of this task.

**Comment by fatso83** [comment]
Vote to close (Ref #41 )

**Comment by pocketjoso** [comment]
Yep. If anything, what we know could aim for is to optimise a sequence of multiple calls, as raised in #41.
