### ISSUE TITLE
Process Multiple URLs

### ISSUE THREAD

**Issue by nbyloff** [pocketjoso/penthouse#110]
Is it possible to feed penthouse a list of URLs to build critical CSS for? First tried a regular loop, but because of the spawn process, it just fires off multiple child processes without ever finishing one:

````javascript

urls.forEach(function(url) {
   penthouse({
        url : url,
        css : './dist/styles/main.css',
        // OPTIONAL params
        width : 1300,   // viewport width
        height : 900,   // viewport height
        timeout: 30000, // ms; abort critical css generation after this timeout
        strict: false, // set to true to throw on css errors (will run faster if no errors)
        maxEmbeddedBase64Length: 1000 // charaters; strip out inline base64 encoded resources larger than this
    }, function(err, criticalCss) {
            if (err) {
              console.log(err);
            }
            console.log('finished'); //never reaches this
    });
});
````

Was looking at trying to block on execution until the first phantomjs process completeled, but not having success there. 

Is this currently possible with this module?

**Comment by pocketjoso** [comment]
Well no there's no support directly in the package for batch handling multiple jobs, but it's easy to do in your own code.

What you wrote above should theoretically work, but as it'll fire of all the jobs in parallel there's a chance it will overload your CPU and crash or hang if the list of urls is too long.

To do it in sequence, you just need to make a new penthouse call from the callback, for example:
```
var urls = ['first', 'second' ... ]

function callPenthouseRecursive (urls) {
  penthouse({
        url : urls.shift(), // grabs the first item from the urls array (and removes it from urls array)
        ....
    }, function(err, criticalCss) {
            if (err) {
              console.log(err);
            }
           // handle your criticalCSS
            console.log('finished'); //never reaches this
           // now start next job, if we have more urls
           if (urls.length !== 0) {
             callPenthouseRecursive(urls)
           }
    });
}
callPenthouseRecusrive(urls)

```

**Comment by pocketjoso** [comment]
I'm closing this for now as I hope my answers suffices. Feel free to continue to comment in here if you have follow up questions!

**Comment by nbyloff** [comment]
And here I was trying to over complicate it. Long work sessions == diminishing returns. Thanks!
