### ISSUE TITLE
Allow for configuring page render timeout

### ISSUE THREAD

**Issue by ndemengel** [pocketjoso/penthouse#113]
I encountered the problem of pages not being completely rendered before generating the critical-path CSS. I've seen that there is a "TODO" comment regarding that point [in the code](https://github.com/pocketjoso/penthouse/blob/d4fec1d32ac9e95b98e6c8de49a65bc2c2974977/lib/phantomjs/core.js#L190).

It would be nice to have that timeout configurable. Or to wait for an element to be present in the page. More generally, we could also accept a predicate function that would tell when some expected condition is true before generating the CSS. This would be configurable as follows:

```js
penthouse({
    generateCssAfter: {  // once the page is loaded, wait for one of the following conditions before processing the css:
         delay: 1000,  // delay in milliseconds
         elementIsPresent: '#some .css selector',  // an element matching the CSS selector is present in the page
         condition: function () {  // or with a predicate (maybe not, that would involve (de-)serializing a function to pass it to phantom...)
             // ...
             return ready;
         }
    }
}, ...);
```

If you like the idea, I will submit a pull request in the next hours (update: I did submit pull requests to better illustrate).

**Comment by pocketjoso** [comment]
Hi, sorry for my late answer. I've been thinking about this for a bit, as I'm not sure whether this is something `Penthouse` should handle.

> pages not being completely rendered before generating the critical-path CSS

Can you expand on this - when does this happen for you?

I remember adding the delay and the comment about it in the source code originally, but I think I did so for bad reasons. For example, content requiring JS to generate on the fly will not be included in the criticalcss - but also shouldn't be, as the first render happens before JS execution.

If you have valid use cases for handling this delay better I'm happy to merge your PR(s). Sorry for leaving them hanging for a while.

Cheers

**Comment by ndemengel** [comment]
Well, thinking about it, I think you are right: it doesn't make a lot of sense, at least for most cases. The problem we have is for the following situations:
* A piece of JavaScript is included in the markup to be able to act very early and improve the placement of some elements that use a complex layout.
* Similarly, we have a banner that appears very early with an animation (for EU cookie law compliance), but we could delay that one a bit.

In those situations, the critical-path CSS doesn't contain the required CSS rules because its generation has been made too early ; but then when loading those pages from scratch, the JavaScript code will modify the DOM before the deferred loading of the non-critical-path CSS took place, so there is a time window where a visible part of the page is not properly styled. I suppose a solution would be to use forceInclude for the CSS classes involved, but it isn't always practical.

**Comment by pocketjoso** [comment]
Did you find a workaround for this?

I had a similar use case a while ago. I solved it outside of Penthouse: I was just maintaining a list of ~ 'non critical early appearing' selectors that I set to display none and appended to the critical css, then I made sure to reset the display in the full css.

**Comment by ndemengel** [comment]
Well, our install script modifies the value directly in penthouse code, after having installed the package :-( (We're using [Ansible's lineinfile module](http://docs.ansible.com/ansible/lineinfile_module.html) for that, but a simple `sed --in-place` would do the trick).

**Comment by pocketjoso** [comment]
I'm still trying to figure out whether this kind of timeout should ever be needed. External JS is no longer [requested when Penthouse loads a page](https://github.com/pocketjoso/penthouse/commit/b91a29efa39e7d8177db0967ccf212d680163115), since `0.8.0` - what version are you using?

I'm guessing you're talking about inlined script blocks.. but if so do they really not work without the timeout?

**Comment by ndemengel** [comment]
We're using version 0.9.7.
And indeed, those are inlined script blocks, and they are executed as soon as possible, but just after the first rendering, as explained above. Anyway, your point still makes a lot a sense to me: I do think we should fix our website, though I would say that it could be interesting to expose the wait/timeout setting and to have a workaround in such situations.

**Comment by pocketjoso** [comment]
I'm closing this for now, feel free to re-open the discussion it becomes relevant again.

**Comment by sjungwirth** [comment]
I'm running into the same issue, trying to implement critical css on a legacy website that is not easily changed. There is some javascript that is modifying the initial layout, moving items around, adding items that don't exist in the page source... I know this is not ideal and shouldn't happen, but the shortest path to being able to add/use critical css is to just increase/configure the `renderWaitTime` variable to slightly higher value.

**Comment by pocketjoso** [comment]
@sjungwirth the first render will happen before any javascript has loaded. By the time your javascript kicks in your full css should be loaded. Are you sure you need the delay feature?

**Comment by sjungwirth** [comment]
Possibly not; I was trying to verify the minimized CSS and I noticed my
above the fold content had some problems because of the JavaScript changes.
It may not be noticeable in a real world scenario where the full CSS is
loading shortly after, but it looked pretty terrible, so I think I'd still
like to have a more complete above the fold CSS since I can't guarantee the
order or timing of the full js/css resources since they will be
non-blocking and asynchronous.

**Comment by pocketjoso** [comment]
@sjungwirth I'm interested in looking in to these kind of bugs, as I know that there are some site configurations with JS that caused `Penthouse` to return incomplete critical css. Is it possible for you to share the url those problems happen with, or perhaps a reduced test case?

**Comment by sjungwirth** [comment]
Hi @pocketjoso, the site I was working with is https://mom.me/. I ended up adding a configurable renderWaitTime param to our fork of the project to get that extra CSS in that might be needed if the main CSS loads slower than expected.

**Comment by pocketjoso** [comment]
I release I never responded here @sjungwirth, sorry about that.
Maybe that site has changed in the meantime, but testing now I get perfect results for critical css generation, without any modified `renderWaitTime`.
