### ISSUE TITLE
Reduce duplicate styles

### ISSUE THREAD

**Issue by jameswilson** [pocketjoso/penthouse#117]
I'm interested in trying to reduce the duplicate styles from my `main.css` that appear in the generated `critical.css` file.

Having an option to split the source source stylesheet into `critical.css`  and `non-critical.css` with no style overlap between the two would be pretty nice.  How challenging would this be to add?  Is it a bad idea?

**Comment by pocketjoso** [comment]
Hi James,
Reducing page weight is always a good goal, but in this case it's
counterproductive. Only the main CSS is cached by the browser and re-used
on later pages/visits. It really only makes sense to extract the critical
CSS if you only have one page on your site.

I'm going to close this, but please continue to comment.

**Comment by jameswilson** [comment]
> It really only makes sense to extract the critical CSS if you only have one page on your site.

I don't understand this option.  Do you use penthouse to create a *different* `critical.css` stylesheet for every page in your site?  If so, I'd be curious how you're scripting that.

The way I'm using penthouse is thusly:

- generate `critical.css` for the homepage, passing in the site-wide common `main.css` which also contains all layout styles and other variants that appear across many pages, I make a point to write my layout styles as concisely as possible and ensure they always get added to `critical.css`.
- place all page-specific styles in separate stylesheets that always get *inlined* on the specific page (or sometimes groups of pages) they are written for.

In this scenario all pages in the site contain:
- inlined css from a single common `critical.css` in header.
- inlined page-specific css in header.
- reference to `main.css` in footer.

In this scenario, it serves no purpose to have rules already in `critical.css` also appearing in `main.css`


I'm really interested to hear if I'm using penthouse in an atypical way.

**Comment by pocketjoso** [comment]
> Do you use penthouse to create a different critical.css stylesheet for every page in your site?

Yes, that is how `Penthouse` is meant to be used. That's the purpose of critical css in general.

> If so, I'd be curious how you're scripting that.

something like:
```
var criticalUrls = [
'pageA',
'/about/someCrazyUrl,
...
]
var mainCss = 'pathToMyCssFile'

criticalUrls.forEach(function (criticalUrl) {
  penthouse({
    url: criticalUrl,
    css: mainCss
  }, function (err, criticalcss) {
    // do something with the result here
  })
})
```

> I'm really interested to hear if I'm using penthouse in an atypical way.

Well, yeah you're doing extra work that you shouldn't have to, maintaining page-specific (kind of) critical css etc.  The whole point of using `Penthouse` is to automate this process. Also like I mentioned before `critical.css` is not to be shared between pages, it needs to be page specific. All you should need is:
* inlined _page specific_ critical.css in header.
* `main.css` in footer

For reasons I've stated before, the main.css needs to be complete, including also the styles inlined in the critical css.

----

I hope this clarifies things. I am curious now why you started inlining page specific critical css to begin with? Was there something missing in the critical css?

**Comment by jameswilson** [comment]
> I am curious now why you started inlining page specific critical css to begin with? Was there something missing in the critical css?

Many of the most important pages in the site, such as those in the checkout process all have lots of custom designed content above the fold, that is specific to each page in the checkout process.  Also, some landing pages in the site are custom and complex enough to not have sharable code, hence the inlined page-specific stylesheets.  I'm able to inline *all* the page specific styles and not be penalized by google for having a literal crap-ton of inline styles at the top of the page (even stuff for below the fold), so this hacky solution worked for my needs and didn't cause me to have to take a step back to think if there would be another way to architect it or even consider a separate critical stylesheet per page solution.

I'm thinking my way might be slightly more scalable, in that I dont have to wait for penthouse to run through 50+ urls to regenerate when a site-wide header changes because it is all in one single critical.css file inlined on all pages.

**Comment by pocketjoso** [comment]
> I'm able to inline all the page specific styles and not be penalized by google for having a literal crap-ton of inline styles at the top of the page

How do you know? Realistically you're probably right, but bloating the html does slow down the first render substantially.

> I'm thinking my way might be slightly more scalable, in that I don't have to wait for penthouse to run through 50+ urls to regenerate when a site-wide header changes because it is all in one single critical.css file inlined on all pages.

Now, when I say one critical css per page, I should be more clear. It's one critical css per ~ template, i.e. if you have a hundred different product pages using the same template but with dynamic data, then they would all share the same critical css. Also, you only need critical css for the pages your users land on. Do you really have 50+ pages matching this criteria?

**Comment by jameswilson** [comment]
> > not penalized by google
> How do you know?

Good PSI scores.  They're lower when not all above the fold stuff is there, but don't appear to be affected negatively when there is "too much" (eg, include stuff from below the fold).    Super embarrassing to admit this, but the inline styles at the top of the page are 26681 bytes. I'm not really noticing any render issues doing this, because we're doing so many other performance tweaks on this site, including dns prefetch and various other front-end perf things.

> Do you really have 50+ pages matching this criteria?
50 was a guess. I just counted and there are 25 page-specific stylesheets.

**Comment by pocketjoso** [comment]
> Good PSI scores. They're lower when not all above the fold stuff is there, but don't appear to be affected negatively when there is "too much" (eg, include stuff from below the fold). 

PSI is a rough guideline for developers, but it shouldn't be used as a golden standard. Sometimes it's just wrong, and there are things it doesn't tell you about.

> Super embarrassing to admit this, but the inline styles at the top of one example page is 26681 bytes. 

So this for example. It's not super bad, but ideally your HTML file should weigh in at under 14kb, so it can be delivered in one chunk. Otherwise it gets broken up and delivered in multiple roundtrips, and each roundtrip has associated latency with is what we're trying to avoid as it's slow on mobile. An inlined css of ~27kb is definitively better than having render blocking external resources in your head, but it is even faster if you can trim the critical css further. But to give you a proper reference - the critical css Penthouse generates for people is often over 20kb (sometimes much more than that), even for just one page.

**Comment by HeroProtagonist** [comment]
@pocketjoso Hi! Want to say that this library is really useful. I see this being brought up a lot and I feel there does exist use cases when this could make sense. 
For instance, I am working on a site where I have per page style sheets and a global one for shared styles. In this scenario, I would not lose any css information when using cached per page stylesheets.
Does this seem valid?

**Comment by pocketjoso** [comment]
@HeroProtagonist It's the same kind of problem still. What styles do you want to extract from the global stylesheet? The critical css for page A? for page B? the critical css used on each individual page? I think that will be a lot of work, and with too small of a benefit in return to be worth it. In addition, you could no longer have any page that didn't use critical css, and you would not be able to rely on any mechanism to avoid serving critical css for users who have already cached your full css.

I think it is always good to consider reducing the amount of bytes we download on our sites, but regarding extracting critical css I still believe it's not something worth doing. Let me know if you think I missed something.
