### ISSUE TITLE
assets paths 404 error

### ISSUE THREAD

**Issue by vlrprbttst** [pocketjoso/penthouse#119]
is there a way to transform the relative paths of the above the fold css? I have a bunch of 404 errors in my console because the above the fold stylesheets looks for assets in the wrong place.

![](http://i.imgur.com/8HljvJC.png)

I can't use absolute paths.

If there's not a way of transforming the paths, is there a way (through comments maybe) to tell penthouse to NOT include bits of css in the above the fold generated stylesheet?

I'm using grunt-penthouse.

**Comment by pocketjoso** [comment]
No, not directly in Penthouse, but it's not hard to write your own code for it. See previous answers:
https://github.com/pocketjoso/penthouse/issues/95
https://github.com/fatso83/grunt-penthouse/issues/9#issuecomment-86381343

Feel free to continue to comment event as I close this.
