### ISSUE TITLE
Multiple url's returning 404

### ISSUE THREAD

**Issue by callazio** [pocketjoso/penthouse#124]
When I put in an array of page URL's it does the job of inserting critical CSS but it returns the CSS of my 404 page. Wich means it doesn't render the pages correctly as soon as I put in more then 1 page. If I only put in the home it works perfect.

Also another small issue, I have to use the online version as source for the URL's. When I would use my .dev domain on my local machine it fails and only inserts a few lines of the body & html tag but nothing else.

**Comment by pocketjoso** [comment]
Hi. Can you please try to describe step by step what you're doing so I can understand and debug. :)

* You're using the online generator - https://jonassebastianohlsson.com/criticalpathcssgenerator
* When you enter your 'home' page url it works fine(?)
* When you enter an array of urls... where? The online generator only supports one url at the time

---

As for using `Penthouse` locally - it does exactly the same thing as the online tool, so it must be receiving some different/invalid html for the url you're trying. Can you opening up a command line and run `curl <your .dev url>` and see that it returns the html you expect? 

--

**Comment by callazio** [comment]
I run Gulp with Penthouse locally on my Macbook. When I use a single URL it does the job correct and inserts the critical CSS from the page I filled in. As soon as I use an array, it generates the critical CSS and inserts it but it's the CSS from my 404 page.

This is my Gulp task:

`gulp.task('inline:css', function(){  
  console.log($pages[0]);  
  penthouse({  
    url: $pages,  
    css: 'assets/css/style.css',  
    width: 1920,  
    height: 1080  
  }, function (err, critical) {  
    var clean = new cleanCSS().minify(critical).styles;  
    fs.writeFile('site/templates/partials/critical.php', '<style>' + clean + '</style>');  
  });  
});`

The second problem is, when I use my dev url. For example, deknock.dev. It returns only a few lines of CSS. Basicly only my html & body tag & font imports. When I try to curl like you said it just returns the full page correct.

**Comment by pocketjoso** [comment]
`Penthouse` doesn't support sending in an array of urls, it just assumes that what you sent was a single url, so I presume somewhere an `<yourUrlArray>.toString()` happens and that the concatenated result of your urls is treated as a `404` by your web server.

For a solution on how to call penthouse multiple times with multiple urls, see [this answer](https://github.com/pocketjoso/penthouse/issues/110#issuecomment-198890121)
---

and btw `Penthouse` already calls `cleanCSS's minify` method before returning so no need for you to do it outside. :)

**Comment by pocketjoso** [comment]
Closing this issue for now as I believe it's just a misunderstanding of how to use Penthouse.

@callazio Feel free to continue asking if you still have problems getting it to work for you.
