### ISSUE TITLE
Online version freezes

### ISSUE THREAD

**Issue by paulalexandru** [pocketjoso/penthouse#126]
Hi, I use the online version of your tool found here:
http://jonassebastianohlsson.com/criticalpathcssgenerator/

When I try to paste my css code into the textarea, the page freezes and I can't do anything further. 
Any solution to this problem?
Thanks

**Comment by pocketjoso** [comment]
Hi @paulalexandru,

If you're using Chrome and pasting a very long css file, this is a well known (browser) bug. You can try in a different browser, or split your css into multiple chunks and use them one by one (just make sure you split them in ways that produce valid css chunks), or you can try the paid https://criticalcss.com service, which doesn't require any css pasting.

**Comment by pocketjoso** [comment]
Will close since no response. Feel free to continue to comment if you have more questions.
