### ISSUE TITLE
No way to generate dynamic file name of output CSS

### ISSUE THREAD

**Issue by joe-smalley** [pocketjoso/penthouse#128]
In the case that you want to generate multiple 'above the fold' CSS files with Penthouse and a processor like Gulp, it is necessary to repeat the function for as many files as needs to be produced. The problem with this is it can get quite long, and repeats the function setup each time, eg:

`
// index
penthouse({
    url : 'http://localhost:4000/index.html',
    css : '../_site/assets/css/styles.min.css',
    width: 1300, // viewport width
    height: 900 // viewport height
}, function(err, criticalCss) {
    if (err) {
       throw err;
    } 
    fs.writeFile(dest +  '/above-the-fold--index.css', criticalCss);
});

// blog
penthouse({
    url : 'http://localhost:4000/blog/index.html',
    css : '../_site/assets/css/styles.min.css',
    width: 1300, // viewport width
    height: 900 // viewport height
}, function(err, criticalCss) {
  if (err) {
      throw err;
   } 
  fs.writeFile(dest +  '/above-the-fold--blog.css', criticalCss);
});
`

etc

Since only the 'url' attribute and the output CSS filename change each time, it would be much nicer to write an array of objects first, eg:

`//Penthouse templates
var penthouseTemplates = [
  {
    cssSuffix: 'home',
    url:  ''
  },
  {
    cssSuffix: 'single-post',
    url:  '/amet-massa-sit-amet-fermentum/'
  },
  {
    cssSuffix: 'articles',
    url:  '/articles/'
  }
];`

And then loop through them, feeding in the cssSuffix and URL attributes which change each time, eg:

`
  for (var i = 0; i < penthouseTemplates.length; i++) {
  
    var cssSuffix = penthouseTemplates[i].cssSuffix;
  
    penthouse({
        url : vhost + penthouseTemplates[i].url,
        css : path.join( dest + '/style.min.css' ),
        width : 1300,   // viewport width
        height : 900   // viewport height
    }, function(err, criticalCss) {
        if (err) {
          throw err;
        }
        fs.writeFileSync( dest +  '/above-the-fold--' + cssSuffix + '.css', criticalCss );
    });
  
  }
`

However this doesn't work because the output file writing happens within a callback function with no access to 'penthouseTemplates[i].cssSuffix' or the current state of 'cssSuffix'.

It would be nice to make Penthouse work within a loop for this reason.

**Comment by pocketjoso** [comment]
I presume [this answers your question](https://github.com/pocketjoso/penthouse/issues/110)? :)

**Comment by pocketjoso** [comment]
Given that I've gotten this question a few times I guess I should add it to the readme. Cheers

**Comment by joe-smalley** [comment]
@pocketjoso Very nearly answers my question - the issue of not being able to dynamically change the filename of the output CSS is still there though

**Comment by pocketjoso** [comment]
Penthouse doesn't write out files for you at all - that's up to you to do. If you use the code I answered with in my reply in that issue you have access to the the url from the array at the top when you get the critical css, and can name the file based on that. If you want to use some additional info, just modify the array to contain more info, perhaps: `[{url:'', name:''},{...}...]`). Does that answer your question? :)

**Comment by pocketjoso** [comment]
Closing as I hope I answered the question by now - feel free to comment again and we can re-open if there's more to discuss.
