### ISSUE TITLE
Penthouse changes z-index values for position:fixed element

### ISSUE THREAD

**Issue by hbaughman** [pocketjoso/penthouse#130]
I have a `position: fixed` nav element above-the-fold with a high-value `z-index`. When you scroll, I want it to appear over other page content. Penthouse is reducing the `z-index` values of all above-the fold content down to the lowest possible numbers while maintaining their sequence. (If you have one element with `z-index: 10` and another with `z-index: 99`, they become `z-index:1` and `z-index:2` respectively.)

Because my fixed nav is the only above-the-fold element with an explicit `z-index`, it gets knocked down to `1`. This subsequently causes it to appear under the other content.

My workaround was to add:

```css
.fixed-nav:after {
  z-index: 1;
}
```

Which causes the `z-index` of `.fixed-nav` to only fall to `2` which (in my case) was sufficient to prevent the problem.

I think it would be preferable to keep all `z-index` as they are explicitly set.

**Comment by pocketjoso** [comment]
Hi,
My first question:

Are you still loading your full css on your page(s)? If so at least then once it loads the problem should go away, as your full css should have the correct z-index values.

Now for the problem in the critical css:
There's no code inside `Penthouse` to change `z-index` values, so I wonder what's going on here.. Can you share the minimal css needed to reproduce the problem? I.e. original css with the z-index you want, and also if you can, what url you're generating it for.

Cheers

**Comment by hbaughman** [comment]
> There's no code inside Penthouse to change z-index values

You're right, apologies for the bother! The problem was the result of my minifying penthouse's output with CSSnano. Collapsing z-index values is [one of their options](http://cssnano.co/optimisations/#zindex) (on by default).

Thanks so much for making penthouse. The way it connects to a url (in contrast to parsing html like critical) makes it a breeze to use for handlebars-based [Ghost](https://ghost.org/) themes.
