### ISSUE TITLE
Update "css" URL

### ISSUE THREAD

**Issue by qasimzee** [pocketjoso/penthouse#140]
Seems like "git://github.com/pocketjoso/css.git" has bin invalid. Can we please update it from "git://github.com/pocketjoso/css.git" to "https://github.com/pocketjoso/css.git"

**Comment by pocketjoso** [comment]
Hi, where do you see this link listed?

**Comment by qasimzee** [comment]
Thanks for very fast response.

Line 30, https://github.com/pocketjoso/penthouse/blob/master/package.json

**Comment by pocketjoso** [comment]
Just quick tip for future - you can highlight lines via url on github (also via clicking on them):
https://github.com/pocketjoso/penthouse/blob/master/package.json#L30

**Comment by pocketjoso** [comment]
Can you tell me more before I make this change - what problem does this invalid bin cause for you? Does `Penthouse` not run?

**Comment by qasimzee** [comment]
During installation on windows, it throws an error.

**Comment by qasimzee** [comment]
Following is the error:

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:477:12)
npm WARN addRemoteGit  git://github.com/pocketjoso/css.git resetting remote C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pocketjoso-css-git-45193baf because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/pocketjoso/css.git C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pocketjoso-css-git-45193baf: Cloning into bare repository 'C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pocketjoso-css-git-45193baf'...
npm ERR! git clone --template=C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/pocketjoso/css.git C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pocketjoso-css-git-45193baf: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/pocketjoso/css.git C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pocketjoso-css-git-45193baf: github.com[0: 192.30.253.112]: errno=Invalid argument
npm ERR! git clone --template=C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/pocketjoso/css.git C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pocketjoso-css-git-45193baf: github.com[1: 192.30.253.113]: errno=Invalid argument
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/pocketjoso/css.git C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pocketjoso-css-git-45193baf
npm ERR! Cloning into bare repository 'C:\Users\qzeeshan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-pocketjoso-css-git-45193baf'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Invalid argument
npm ERR! github.com[1: 192.30.253.113]: errno=Invalid argument
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\qzeeshan\Documents\penthouse\npm-debug.log

**Comment by pocketjoso** [comment]
Fixed in 0.10.2 thanks to #141 - thank @qasimzee!
