### ISSUE TITLE
Error: cannot read config.json

### ISSUE THREAD

**Issue by nachtfunke** [pocketjoso/penthouse#142]
I am using penthouse with grunt, so I installed the grunt-penthouse plugin. It installs penthouse, which then again installs phantomjs. In your repo, there is a config.json, but when I try to run it, it throws an error, saying that config.json is not readable. When I looked into the lib/phantomjs folder, I realized that the config.json file was missing. Is this intentional?

**Comment by pocketjoso** [comment]
Hi, thanks for raising this issue, seems like a bug.
Can you try installing `penthouse@0.10.3-rc` to confirm it gives you the missing file?

**Comment by pocketjoso** [comment]
@nachtfunke Did you have a change to test this fix?

**Comment by pocketjoso** [comment]
Tested myself, is indeed fixed by #144.

Now in `latest` (0.10.3).
