### ISSUE TITLE
Improve: Extract the CSS from the HTML - do not ask for it

### ISSUE THREAD

**Issue by josenobile** [pocketjoso/penthouse#146]
You can extract the CSS from the page using the same technique to reject js, but instead filtering the CSS and using it. Does make sense?

**Comment by pocketjoso** [comment]
[critical](https://github.com/addyosmani/critical) does this, so does the paid https://criticalcss.com service.

I prefer keeping `Penthouse` focused on one thing. Feel free to continue to comment if you disagree.

**Comment by josenobile** [comment]
Hello, 

You focus on calculate css priority, is OK. But, this is about input parameters, not the operation itself. You already are using phantomjs, you can intercept the requested CSS files and load their content.

**Comment by pocketjoso** [comment]
The two tools I linked to above do what you ask for. Did you try them?

**Comment by josenobile** [comment]
Yes, I did. But Penthouse is the only supporting pass directly the HTML code, not a URL.

**Comment by pocketjoso** [comment]
From the critical readme:
```
critical.generate({
....
    // HTML source
    html: '<html>...</html>',
```

That's what you're looking for, right?

**Comment by josenobile** [comment]
Excuse me, yes.
