### ISSUE TITLE
How to use elements attributes in forceInclude?

### ISSUE THREAD

**Issue by loheswaran** [pocketjoso/penthouse#155]
Using **forceInclude**, I can give the classes to be part of the final output file even if it is not seen in the DOM. Is there away give **hide** attribute as the input to **forceInclude**?
**CSS :**
[hide] {
display: none;
}
**DOM :**
\<div hide\>\</div\>

**Comment by pocketjoso** [comment]
Yes, just use:
forceInclude: '[hide]'

As the reader says, you can also use regexes for the forceInclude.

**Comment by loheswaran** [comment]
Thanks. It worked.
One more issue.  It seems, it's not considering the classes of the DOM elements that are created through javascript?

**Comment by pocketjoso** [comment]
Yes, as javascript is only run after the first render. By that time you should have your full css loaded.

**Comment by loheswaran** [comment]
It means, it will not work for the elements that are dynamically created through javascript. Because mine is an angular application and all the body content has been split into different widgets(templates). All the widgets are rendered through angularjs.
Is there a way to make it work with my application

**Comment by pocketjoso** [comment]
To get good performance of your application you need to server render the content. There's no other way around that.

**Comment by loheswaran** [comment]
Thanks for clarifying.
