### ISSUE TITLE
Error opening url

### ISSUE THREAD

**Issue by malinky** [pocketjoso/penthouse#160]
Hi, I've be using penthouse successfully for a while but have just migrated by website to use https. Now when I run my gulp task I get error opening url and I'm not sure how to fix it as the url seems to work correctly in my browser. This is the output.

time: 39 | opened css
time: 45 | prepared new page
time: 106 | parsed ast (without errors)
time: 107 | getCriticalPathCss
time: 109 | stripped out non matching media queries
time: 2022 | ERR: Error opening url 'https://www.fine-turf.co.uk': Connection closed

Can you help at all please. Thanks

**Comment by pocketjoso** [comment]
Sounds like there could be an issue with your SSL setup, however when I run penthouse towards your url myself it works without any problems.

Can you double check that `node_modules/penthouse/lib/phantomjs/config.json' exists on your file system? (i.e. [this file](https://github.com/pocketjoso/penthouse/blob/master/lib/phantomjs/config.json).

Finally, what version of Penthouse are you on?

**Comment by malinky** [comment]
I have the config file mentioned and I was running 0.9.7. I've updated to 0.10.9 and I'm still facing the same issue. I can open https urls from other sites but not this one. I'm out of ideas if there is anything else you think of please let me know. Otherwise thanks for your help anyway.

**Comment by malinky** [comment]
I've just fixed the problem by adding the option below into the Penthouse setup so there must have been an error for me with the sslProtocol used in the config file. Thanks again for your help and this package.

```
phantomJsOptions: {
  'ssl-protocol': 'any',
},
```
