### ISSUE TITLE
Avoid "css" dependency from GitHub

### ISSUE THREAD

**Issue by oskarrough** [pocketjoso/penthouse#162]
Hi, currently the `css` package is defined without a version like this:

```
"css": "https://github.com/pocketjoso/css.git",
```

.. unfortunately this breaks builds with different yarn/npm versions not able to figure out the url. Sometimes it does work though.

In any case, would it be possible to instead use a tagged version from npm?

**Comment by pocketjoso** [comment]
Hi,
seems to be am old [npm dependency install issue with git urls](https://github.com/npm/npm/issues/3055), that perhaps yarn inherited?

I'm using a fork of the `css`, to make the css parser more forgiving towards errors in the css. I don't want to publish a separate npm package just for a fork with a handful of extra commits.

I've never hit this issue myself, what's the exact error?

**Comment by oskarrough** [comment]
Well, this is typical, sorry. Had the issue for weeks and today it just works. For the record, I am using `penthouse` through the `critical` module.

Previously it would fail with: 

> `yarn.lock` file is stale! Missing entry for "css@https://github.com/pocketjoso/css.git". Please regenerate by running `yarn`.

... even though I did clear and regenerate. I'll close. Thank you!

**Comment by oskarrough** [comment]
OK, now I have it again. It only happens when I deploy via now.sh. The error I see is:

```
> Error: Error 500 from http://10.100.202.49:3000/pocketjoso/css.tar
>     at _callee15$ (/usr/lib/node_modules/@zeit/ace/build/install.js:903:21)
>     at tryCatch (/usr/lib/node_modules/@zeit/ace/node_modules/regenerator-runtime/runtime.js:65:40)
>     at Generator.invoke [as _invoke] (/usr/lib/node_modules/@zeit/ace/node_modules/regenerator-runtime/runtime.js:303:22)
>     at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/@zeit/ace/node_modules/regenerator-runtime/runtime.js:117:21)
>     at step (/usr/lib/node_modules/@zeit/ace/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
>     at /usr/lib/node_modules/@zeit/ace/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
>     at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by pocketjoso** [comment]
Okay, let's keep this open. At this point I don't have a plan for how to resolve this - if you come across any solution (that keeps the git dependency), please let me know.

**Comment by oskarrough** [comment]
Me neither. But sure thing, thank you

**Comment by oskarrough** [comment]
The bug hunt continues!

```
warning Pattern ["css@https://github.com/pocketjoso/css.git"] is trying to unpack in
the same destination 
"/Users/oskar/Library/Caches/Yarn/v1/npm-css-2.2.1-8ddea7e3cbc0a183ecf694a7a5fbc84326893893" 
as pattern ["css@^2.2.0","css@2.2.1","css@^2.1.0"].
This could result in a non deterministic behavior, skipping.
```

**Comment by pocketjoso** [comment]
Thanks for more info.

**Comment by vvo** [comment]
What I am used to do when I do fork projects and need the npm dependency and don't want to tackle the kind of bugs we are discussing here is that I do:

name: 'package-fork-vvo',
version: 'bump'

then npm publish.

This would resolve this issue and provide users a safe env to run your code (because it's actually versionned, not just "latest git").

**Comment by jchip** [comment]
Our internal sec team doesn't allow our build machines to access github.com.  I've published the css package from https://github.com/pocketjoso/css under the name pjcss.  would it be possible to update this to use that?

**Comment by pocketjoso** [comment]
Should be fix in the latest version, following recommendation from @vvo.
Can you please try penthouse@v0.11.13, or if you want to try the absolute latest, penthouse@next, which uses Chrome headless and offers a 2x speedup (but beware as it still requires some more testing - pr here: #174 ).

**Comment by jchip** [comment]
cool.  thanks.  

I notice that `apartment` also depends on `css`, is that going to be an issue?

**Comment by pocketjoso** [comment]
No, since it uses the original version. Penthouse uses a fork to be able to
better handle parsing invalid css.

**Comment by pocketjoso** [comment]
This has been fixed.
