### ISSUE TITLE
Feature Request - Multiple viewport sizes

### ISSUE THREAD

**Issue by diginfo** [pocketjoso/penthouse#171]
Thanks for developing penthouse, I have it installed under nodejs and it generates minified css for all the pages on the site.

I am trying to achieve 100% with google page speed insights, and while I can do that for desktop, mobile always fails.

It would be really great to be able to have the css file consolidated with desktop and mobile css.

I tried this by running it twice and concat the result, once for each resolution, but this results in duplicates.

**Comment by pocketjoso** [comment]
Hi,

> I am trying to achieve 100% with google page speed insights, and while I can do that for desktop, mobile always fails.

In what way does it fail on mobile?

Normally you don't have to do anything to create a special "mobile" critical css, just as you don't normally serve two different stylesheets. As long as you're site is using the same html markup for different viewport sizes, and uses responsive design (i.e. media queries) to achieve any changes in the site between different viewport sizes - the critical css will work for both mobile and desktop.

So if this is not the case for you, then something is going wrong. Let me know what details you have, even if you can share the url for your site (via DM if you don't want to share here), then I can take a closer look.

Regarding the feature you are asking for - as I don't want to encourage people to create separate critical css files as it is not necessary, it is not likely that I will add such a feature.

Cheers,
Jonas

**Comment by diginfo** [comment]
Thanks for responding;

Yes, I am using semantic UI, and can achieve 100% on some pages for desktop, but only 85% with mobile, and it is serving the same html/css pages for both with media queries.

I will DM you with the page I have been testing on, it would also be good if penthouse could write 2 files, one for above the fold, and another for below it, as the semantic (and other css frameworks) can be quite large and I have to load the full css (deferred) as a link as well as the inline css generated by penthouse and this results in duplicate css inline and as a file download.

**Comment by diginfo** [comment]
There does not appear to be any Direct Messaging on github, so I sent you a message via email on your website.

**Comment by pocketjoso** [comment]
> Yes, I am using semantic UI, and can achieve 100% on some pages for desktop, but only 85% with mobile, and it is serving the same html/css pages for both with media queries.

Okay, but what are the warnings when you get 85%? Are you sure the relate to the critical css?

> it would also be good if penthouse could write 2 files, one for above the fold, and another for below it, as the semantic (and other css frameworks) can be quite large and I have to load the full css (deferred) as a link as well as the inline css generated by penthouse and this results in duplicate css inline and as a file download.
This has been [discussed many times](https://github.com/pocketjoso/penthouse/issues/117#issuecomment-202744247) - I should really put it in the FAQ: you need the full styles to be complete, so they can be cached and re-used on subsequent pages.

**Comment by pocketjoso** [comment]
@diginfo I did not receive any email from you yet. Will check later, otherwise try somewhere else, like twitter, where I have the same handle as here.

**Comment by diginfo** [comment]
The problem is if you are using a framework (such as semantic UI) , there is a lot of css in these frameworks that you may not use, and while penthouse fixes the above fold, I still have the problem of the full css file blocking rendering as it is bloated with unused css.

PSI is complaining that the full css contains too much un-used css and it is this that is hurting the score on mobile wheras it is 100% on desktop.

**Mobile: 85%:**
```
Your page has 1 blocking CSS resources. This causes a delay in rendering your page.
Approximately 31% of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
```

**Desktop 100%**
```
Great job! This page applies most performance best practices and should deliver a good user experience.
Congratulations! No issues found.
```

**Comment by diginfo** [comment]
Semantic UI is modular and I have selected the components I need and combined them into a single css minified file that is used for all pages, this is the 'full css'.

But for example, the button.css component is 86k minified, so if you only use 1 button and 1 style, then 99% of this css file is unused, but you cannot just extract the small bits that you use.

What I need is to be able to extract the total used css (as a deferred, linked css) , and the above fold inline css, and this problem would be solved.

**Comment by diginfo** [comment]
sorry for all the posts, but as I think of something useful, I am adding it.

Actually **penthouse is doing it's job correctly**, there's no problem with the functionality.

My problem is I need to remove the un-used css from the full css file which is defer loaded externally, this is what is hurting my rankings.

**Comment by pocketjoso** [comment]
@diginfo You're misunderstanding PSI's feedback.

> Your page has 1 blocking CSS resources. This causes a delay in rendering your page.

What this error means is that you have a block `<link rel='stylesheet.... />` element in the `<head>` of your document, which if so nullifies the benefits you get from critical css.
PSI is not very reliable on this point however, I often see it misidentified javascript injected stylesheets for being render blocking (which they are not), so this might be the case here, especially if you get no warnings for desktop (with same html).

> Approximately 31% of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.

What they are saying here is that 69% of your content was blank in the first render, i.e. the critical css didn't contain the styles required. PSI also provides links to `see screenshot` when this error is present, so you can see exactly what PSI thinks the first render looks like. Again, I'm inclined to think that PSI is wrong here (as it sometimes is on this point as well), primarily because you say you don't get this warning on desktop.

> My problem is I need to remove the un-used css from the full css file which is defer loaded externally, this is what is hurting my rankings.

Sounds like you need [uncss](https://github.com/giakki/uncss)?
Note however that PSI does not complain about the size of your full stylesheets, but that being said:

> ...the button.css component is 86k minified

That sounds unbelievable. I can hardly believe that it's 86kb on disk... that would be a loooooot of css for one element.

**Comment by pocketjoso** [comment]
@diginfo I will close this due to inactivity. Feel free to comment again and I can re-open it.
