### ISSUE TITLE
Check for node version on postinstall script

### ISSUE THREAD

**Issue by reznord** [pocketjoso/penthouse#175]
Right now we are not checking for node version. It would be better to have a check where we throw an error if the node version is less than the required (specified in `engines` in package.json)

**Comment by pocketjoso** [comment]
Good idea - feel free to make a PR!

**Comment by reznord** [comment]
What node version should I check for now? Asking coz, headless-chrome PR is almost completed.

**Comment by pocketjoso** [comment]
If you make the pr towards #174 then the minimum version is `7.10`. Cheers

**Comment by pocketjoso** [comment]
So as mentioned in the PR - Puppeteer already checks node version during install time so let's leave this for now, we can always raise the issue again should we move from Puppeteer again in the future (unlikely in the short term).
