### ISSUE TITLE
replace internal puppeteer pages counting

### ISSUE THREAD

**Issue by pocketjoso** [pocketjoso/penthouse#184]
Once https://github.com/GoogleChrome/puppeteer/pull/554 lands.

**Comment by Saturate** [comment]
It's landed if anyone was wondering.

**Comment by pocketjoso** [comment]
Great, thanks for the notification! Are you interested in making a pr for it? Otherwise I'll get to it eventually.

**Comment by Saturate** [comment]
Sure, I might take a look at it :-)

**Comment by pocketjoso** [comment]
This was done (https://github.com/pocketjoso/penthouse/pull/271)
