### ISSUE TITLE
Quotes get omitted, eg custom font family

### ISSUE THREAD

**Issue by patrickhaug** [pocketjoso/penthouse#187]
when you include a custom font and have it like:

```
.font {
 font-family: 'custom-font', Arial, Tahoma;
}
```
it reults in:

```
.font {
 font-family: custom-font, Arial, Tahoma;
}
```

**Comment by pocketjoso** [comment]
is that a problem? as long as your custom font does not contain any spaces in the name, it will be interpreted the same by the browsers.
