### ISSUE TITLE
Asynchronous

### ISSUE THREAD

**Issue by rogerbeckers** [pocketjoso/penthouse#192]
Hi,

I have an problem with using Penthouse version 1.x.x, the new version of penthouse is Asynchronous. I need to run the code synchronous because i call a script from PHP (exec) and i don't get the complete output. Is this possible ?

Thanks!

**Comment by pocketjoso** [comment]
Penthouse has always been async, and you are still able to use exactly the same invocation pattern as in the original version (i.e. callbacks ~ `penthouse(settings, callbackFn)`), although it's recommended to use Promises.

**Comment by rogerbeckers** [comment]
_**Thanks for your info, i'm getting this error while executing through PHP (exec()). Command line the script is working perfectly;**_
 "Unhandled Rejection at: Promise Promise {",
        "  <rejected> { Error: spawn EACCES",
        "    at exports._errnoException (util.js:1050:11)",
        "    at ChildProcess.spawn (internal/child_process.js:319:11)",
        "    at Object.exports.spawn (child_process.js:378:9)",
        "    at Function.launch (/*****/public_html/v1/node_modules/puppeteer/lib/Launcher.js:100:40) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' } } reason: { Error: spawn EACCES",
        "    at exports._errnoException (util.js:1050:11)",
        "    at ChildProcess.spawn (internal/child_process.js:319:11)",
        "    at Object.exports.spawn (child_process.js:378:9)",
        "    at Function.launch (/*****/public_html/v1/node_modules/puppeteer/lib/Launcher.js:100:40) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }"

_**The code causes this error;**_
penthouse({
		url : aCurrentData.url,
		css : path.join('../tmp/' + aArguments.filename),
		width : 1300,
		height : 900,
		timeout : 30000,
		renderWaitTime : 100,
		strict : false
	}, function(err,output){ console.log('test'); });

_**PHP;**_
exec('node critical.service.js \'' . $sData . '\' 2>&1', $aDataNode, $err);

**Comment by pocketjoso** [comment]
Sounds like a permissions/setup problem, and is related to  [puppeteer](https://github.com/GoogleChrome/puppeteer). Can you verify that you can run puppeteer on your platform, via php?

**Comment by rogerbeckers** [comment]
Problem solved, it was a permission problem. Thanks for your support.
