### ISSUE TITLE
Passing puppeteer browser in options

### ISSUE THREAD

**Issue by bitriddler** [pocketjoso/penthouse#198]
Sometimes to generate critical css I need to do a couple of things (e.g. login user).

I'm not sure what's the best way to do that, but it would be great if I can create puppeteer browser, do some stuff then pass it to penthouse.

If that makes sense then I can make a PR for that?

**Comment by pocketjoso** [comment]
Hi,
Thanks for raising this issue. Just to confirm before I look at your PR - are you needs greater than what could be achieved by just using basic (username/password) authentication, i.e:
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageauthenticatecredentials

I suspect it is, just want to check.

**Comment by pocketjoso** [comment]
I also reviewed your PR, because I suspect it can be useful for others in either case.
