### ISSUE TITLE
Document how to enable DEBUG logging

### ISSUE THREAD

**Issue by Saturate** [pocketjoso/penthouse#205]
Right now it's not clear how to enable debugging. This could be documented, and it could be considered if the use of `debugjs` would make sense, especially when the `puppeteer` package uses it. 

https://github.com/GoogleChrome/puppeteer/#debugging-tips

**Comment by pocketjoso** [comment]
Makes sense - thanks for the issue. Feel free to open a PR for it, otherwise I'll get to it eventually - but could take some time for.

**Comment by Saturate** [comment]
Sure, I'll make a PR.
