### ISSUE TITLE
fault tolerant CSS AST parsing

### ISSUE THREAD

**Issue by pocketjoso** [pocketjoso/penthouse#208]
This has long been a problem for penthouse, as the current [css](https://github.com/reworkcss/css) parser is not fault tolerant, and (in best case) throws when there's anything in the input css it doesn't understand.

The goal here would be to switch to an ast parser that is:
- as fast as possible
- as fault tolerant as browsers (i.e. [the spec](https://www.w3.org/TR/css-syntax-3/#error-handling))

Promising alternative parsers are:
- [csstree](https://github.com/csstree/csstree) @pocketjoso looking into it, will open PR soon
- [CSSOM](https://github.com/NV/CSSOM)
- [postcss](https://github.com/postcss/postcss) + [postcss-safe-parser](https://github.com/postcss/postcss-safe-parser) @bradlc has something working, will open PR

(this list was found via [ast explorer](https://github.com/fkling/astexplorer/blob/master/README.md))

**Comment by bradlc** [comment]
Hey @pocketjoso 

I managed to swap in PostCSS (with the safe parser) a while ago. I can take a look at putting together a PR this week if you like?

**Comment by pocketjoso** [comment]
@bradlc Ah, I should have opened an issue for this earlier! By now I already came 75% or so towards a csstree implementation. So what I suggest is we both open PR's, and then we compare which one is better - primarily determined by:
- fault tolerance (probably 100% on both)
- execution speed
(and to some extent, cleaner code, but less important for me).

So yeah if it doesn't take too much of your time I would still love to see a PR. But do note that I myself chose csstree because it looked like it would have the best performance, so perhaps I'm leaning towards using this solution - but I would prefer to let our numbers speak! (and how to compare - partially from running the test suites, but I can also setup https://criticalcss.com to run some of it's jobs on these versions to get some large numbers of generation jobs with each version).

Cheers to open source collaboration! 🥂

**Comment by pocketjoso** [comment]
As part of this move to fault tolerant css parsing, the use of [reworks css ast parser](https://github.com/reworkcss/css) has to be phased out (as it is not fault tolerant).

One place this is used is with @bevacqua 's [apartment](https://github.com/bevacqua/apartment) library, [on these lines](https://github.com/pocketjoso/penthouse/blob/master/src/postformatting/index.js#L35-L39). @bevacqua are you interested in updating to your library to switch ast parser/approach, or should I rather look at refactoring this code myself (if so removing your library as a dependency)?

**Comment by pocketjoso** [comment]
(closed by mistake)

**Comment by pocketjoso** [comment]
Opened a PR for using `csstree` as the AST parser now - ~ 90% done.
cc @bradlc

**Comment by pocketjoso** [comment]
And yeah last update @bradlc I will probably merge my PR since it is working well - but I am still open to completely replacing that code if you open a PR that has better results. I do understand if you're less motivated given that I will already have filled the need - so up to you!

**Comment by bradlc** [comment]
Hey @pocketjoso 

Sorry I didn't get chance to look at this yet. If csstree is working well then maybe just stick with that? The only reason I used PostCSS was because I was aware of it and it's a very popular and well-maintained project. I doubt there would be a significant difference in performance between the two.

If there are any other issues you need a hand with I would definitely be interested in helping out!

**Comment by Kamshak** [comment]
Great initiative! Having some trouble with using penthouse on minified CSS (bootstrap) and seems that this could be causing it. Can't wait to see this land on master :+1:
