### ISSUE TITLE
Removing dublets

### ISSUE THREAD

**Issue by ChristianLJ** [pocketjoso/penthouse#210]
Hi there!

I am using Penthouse for our webshop and it works like a charm.

Penthouse generates a .php file with all my critical CSS. The file is generated from my styles.css and is included in my header as critical-css.php.

Afterwards i generate a styles.min.css and load it in the footer.

In this way i end up with duplicated CSS content since the same CSS is present in styles.min.css and critical-css.php

Is it possible to remove all generated critical CSS from my styles.min.css after the critical CSS is generated?

Thank you.

**Comment by pocketjoso** [comment]
Hi,
This duplication is necessary as only the full styles are cached by the browser and re-used on later page loads.

You can also see me previous answer [here](https://github.com/pocketjoso/penthouse/issues/117#issuecomment-202744247).

Closing as a duplicate.
