### ISSUE TITLE
Requiring ESLint as a peer dependency

### ISSUE THREAD

**Issue by devmattrick** [pocketjoso/penthouse#212]
Hi there!

I think the recently merged pull request (#207) creates the issue npm throwing warnings that ESLint is missing as a peer dependency, since many of the ESLint configs and plugins require ESLint as a peer dependency:

```
npm WARN eslint-config-prettier@2.9.0 requires a peer of eslint@>=3.14.1 but none was installed.
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint@>=3.19.0 but none was installed.
npm WARN eslint-plugin-import@2.8.0 requires a peer of eslint@2.x - 4.x but none was installed.
npm WARN eslint-plugin-node@5.2.1 requires a peer of eslint@>=3.1.0 but none was installed.
npm WARN eslint-plugin-standard@3.0.1 requires a peer of eslint@>=3.19.0 but none was installed.
```

Running `npm ls` on one of these returns:
```
$ npm ls eslint-config-standard
example@1.0.0 D:\Matthew\Documents\Projects\example
`-- critical@1.1.0
  `-- penthouse@1.2.0
    `-- eslint-config-standard@10.2.1
```

I think the easiest solution would be to move everything ESLint related to `devDependencies`. As far as I know, there's no need to include those in the "production" version.

Thanks!

**Comment by pocketjoso** [comment]
Thanks for issue - will be resolved in next release (soon).
