### ISSUE TITLE
Supporting `package-lock.json`

### ISSUE THREAD

**Issue by Saturate** [pocketjoso/penthouse#235]
Hey,

While looking at another package, I noticed that they only supported a `yarn.lock` file, this is great if you are using Yarn. It will lock the packages and make sure that you get a consistent result.

However if a user is using NPM for some reason, the packages aren't locked. This can course all kinds of trouble if the underlying packages misuses semver. This has happened before (not here that I know of). It will be hard to get reproducible build without.

Maybe it would be a good idea to support both? However, it will be way harder to maintain. What's your take on this?

**Comment by pocketjoso** [comment]
I'm not sure what your use case is, are you talking about as a contributor to Penthouse, or as a user of it?

For the latter, the [exported penthouse module](https://unpkg.com/penthouse@1.4.0/) doesn't contain the `yarn.lock` file and doesnt doesn't care whether you use yarn or npm - only the package.json is used for dependencies.

For the former, as a contributor to any project you will have to setup the tools required, and for Penthouse, yarn is one of them. I don't want to have to support both npm and yarn, sorry. I'm open to moving back to npm in the future.

**Comment by Saturate** [comment]
This was just something that I was thinking a, but from a users perspective. I guess the `package-lock.json ` file is import when depending on penthouse as well, I have i misunderstood something about npm?

Contributes should just use yarn :-)

**Comment by Saturate** [comment]
This was never really an issue, just something that I were thinking about. But I can see the error in my thinking now. I'll close this.

Thanks!
