### ISSUE TITLE
Relative Paths within CSS = Problem

### ISSUE THREAD

**Issue by futureweb** [pocketjoso/penthouse#238]
Hey there,
got some Troubles with relative Pathes within CSS (bootstrap.css):

CSS File: /path/to/css/bootstrap.css
CSS with relative Path: url("../fonts/bootstrap/glyphicons-halflings-regular.ttf")
Path of Font: /path/to/fonts/glyphicons-halflings-regular.ttf

Now when I inline the resulting CSS - the Path to the Font, of course, is broken. Also if I save the exported critical CSS to another Path than the Original - Font is broken.

Any ideas on that? ;-)

thx, bye from sunny Austria
Andreas Schnederle-Wagner

**Comment by pocketjoso** [comment]
Penthouse does not get involved in the path rewriting as it only receives a css string, and does not know where in your file structure this css is supposed to live.
You have to either:
- only use absolute paths
- rebase all relative paths yourself after generating the critical css (if all css came from the same file it's a relatively simple process since the rebase operation will be exactly the same for all relative paths)
- use a higher level tool that operations on html page levels and handles path rebasing for you, for example https://github.com/addyosmani/critical and https://criticalcss.com (paid SAAS, my own creation).

**Comment by futureweb** [comment]
thx for your super-fast answer! :)
I've done it with 'sed' afterwards now ...

One further Question - is there the possibility to check multiple Pages for critical css?

**Comment by pocketjoso** [comment]
Assuming that I understand you correctly - just run penthouse multiple times, one for each page. You can run the calls in parallel if you need them to happen fast.

Why not combining in one call? Critical css is per page, you don't want to combine it for multiple pages _unless_ they really are instances of the same kind of page template with minimal variation. All styles for all elements in view on page load must be part of the critical css, and if you start combining for different pages the size will blow up and you will no longer get the full performance benefits.

**Comment by futureweb** [comment]
ok - guess I need to dive a bit depper in the "above the fold" / "critical css" thing ... :-)

my fear is that if I create a critical css per page - the overhead it creates (one more css to download per page) is more negative than the positive aspects ... is this fear unfounded?

**Comment by pocketjoso** [comment]
> my fear is that if I create a critical css per page - the overhead it creates (one more css to download per page) is more negative than the positive aspects ... is this fear unfounded?

With the simplest implementation you will indeed be downloading extra bytes, but:
- clearing the critical path and using critical css will improve your first render times by seconds (exact times depends on your site)
- the critical css should be small, ideally under 14kb, so compared to your site as a whole it should not be very heavy

Further if you want to absolutely optimize things (but this is really less important) you can set a cookie once your regular css has loaded, and then stop serving the critical css. It is only needed for the first load, after that the full css should be cached and served immediately. If you do go down this path though, then you need to make sure you invalidate that cookie as soon as your css changes.

**Comment by futureweb** [comment]
alright - thx for your info on this! ;-)

Right now I made the critical css only for the Start-Page which accounts for about 75-80% of First-Loaded-Page ... for Sub-Pages the full css should already be cached ... guess that's  enough for the first step into this direction! ;-)
(was not sure if it's only the download of the full css file which is blocking or also the processing/rendering)
Google PageSpeed gives me 99% now ... guess that's OK ... hehe ;-)
[](https://www.futureweb.at/)

thank you again! ;-)
Andreas

**Comment by pocketjoso** [comment]
👍
