### ISSUE TITLE
forceInclude + combined css selectors = problem?

### ISSUE THREAD

**Issue by futureweb** [pocketjoso/penthouse#242]
hey there,

got some combined css selectors like this:

```
.carousel.fade {
 opacity:1
}
.carousel.fade .item {
 -moz-transition:opacity .7s ease-in-out 0s;
 -o-transition:opacity .7s ease-in-out 0s;
 -webkit-transition:opacity .7s ease-in-out 0s;
 transition:opacity .7s ease-in-out 0s;
 left:0 !important;
 opacity:0;
 top:0;
 position:absolute;
 width:100%;
 display:block !important;
 z-index:1
}
```

Just can't figure out how to force include them?
tried several ways ...

```[forceInclude : ['.carousel', '.fade', '.carousel.fade', '/.*fade.*/'],```

any ideas on that?

thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by futureweb** [comment]
ok ... me dumb ... just noticed that those classes are in another css file ... and not the one I tell penthouse ...
now I'm concatenating all CSS into temporary one and pass this one to penthouse ...

**Comment by pocketjoso** [comment]
👍 
If you need to use the forceInclude prop later, the way to write what you wanted would be:
Either each selector explicitly listed (won't match anything else),
`['.carousel.fade', '.carousel.fade .item']`
Or with a more generic regex:
`[/\.carousel\.fade/]`
