### ISSUE TITLE
Option 'forceExclude'

### ISSUE THREAD

**Issue by futureweb** [pocketjoso/penthouse#243]
Hey there,
would it be possible to implement a 'forceExclude' Option just like 'forceInclude'?
Just noticed a few Styles I don't really need on initial Rendering as they aren't visible.
Guess this would make a good addition to this already pretty cool Project?! ;-)
thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by pocketjoso** [comment]
This sounds like a bug. Something that is not visible in the critical
viewport should by definition not be part of the critical css. Do you have
a concrete example with a public url and a class you are not expecting to
be included, that I can debug?

**Comment by futureweb** [comment]
example: https://www.futureweb.at/?testCriticalCSS=1 (only critical css is loaded here)
I don't need all those *blueimp* Child Styles within critical CSS.

**Comment by pocketjoso** [comment]
The reason they are showing up is because the `blueimp-gallery` element is in the critical viewport (position absolute/fixed, top,left,bottom,right: 0) (a version of the problem in the readme: https://github.com/pocketjoso/penthouse#early-dom-content-moved-out-of-critical-viewport-via-css). I understand your situation:  you set `display: none; opacity: 0` on this element, so you cannot see it, hence you think the styles should not be considered critical. Penthouse just cannot automatically make such inferences.

You can make this style disappear from the critical css by avoiding setting `top: 0` until you start showing the gallery (make sure it's outside of the critical viewport).

So in the end this is and edge case based on your styles. Let me know if you test my solution and how it works for you.
 
I don't really want to add in a forceExclude feature to support - I prefer trying to explain why this happens and how to fix it. I'll look into updating the readme to cover this case (element considered critical even though visually hidden).

**Comment by futureweb** [comment]
Hey Jonas,
sorry for the late reply - was quite busy last week! ;-)

The Problem here is that those Elements are set by a 3rd-Party Module (https://github.com/blueimp/Gallery) and not by me - and one can imagine that I can't edit the CSS delivered with those Modules (... welcome to upgrade hell ...), and I guess that's not the only 3rd-Party-Module which does so?! :-/

I can understand why you try to avoid adding a forceExclude Option - but IMHO for such edge cases it could be helpful to give penthouse some "hints" what to exclude to get smaller critical file size ... 
(guess having such an Option at Hand when don't you need it wouldn't harm anyone - instead of not having such a Option when needed like in this case ... ;-)

Maybe you give the Option a chance? ;-)

bye from sunny Austria
Andreas

**Comment by pocketjoso** [comment]
Okay I'll consider it.

While it's not there, I imagine you could still do something like:
- either not initilize the gallery until you after page load, possibly even leaving the blueimp gallery markup out of the initial html
- or override the default styles, adding ~ `position: relative` to the gallery for default styles, then adding back `position: fixed` when it's showing.

Either of these would take the gallery element out of the critical viewport and remove it from the critical css.

I have understood your point though that this is a bit more work for you and that you are dependent on your library so not in full control. I will research the use case a bit more and possibly add in forceExclude or ~~ ignore to next release.

**Comment by futureweb** [comment]
Hey Jonas,

sounds good - thx! ;-)

As for your suggestions - leaving out the Gallery Markup (or modify in any other way) isn't that easy as it's added by our SAAS CMS to every Page ... would affect thousands of pages at once ... no chance to check them all after doing such changes ... would need really ugly exceptions ... "if above fold optimizations and this and that is activated then don't insert it into page footer ... but later on ..."

For me a forceExclude Option is pretty much the same as the forceInclude Option - I - as a coder - can override the behaviour of a Programm if needed / if I think I know it better than the Program ... ;-)

bye out of the Mountains of Austria
Andreas

**Comment by Odisseya** [comment]
Hi, as for me, exclude option will be much usfull to handy remove rules from `display: none` elements below the fold. @pocketjoso, thanks for your work! Please consider about this.

**Comment by pocketjoso** [comment]
@Odisseya These rules should only be kept in the critical css if they apply for elements that show _above the fold_, i.e. in the critical viewport. If that's not the case, can you give me a (public) URL where you see this unwanted behavior so I can check what's happening?

**Comment by Odisseya** [comment]
@pocketjoso There are few instances, with 2 versions (2 URLs) in each of them: 
1) With critical css — includes unwanted behavior.
2) Pure — without critical css.

**Instance#1** 
URL: [http://odisseya.github.io/criticalcss/1/](http://odisseya.github.io/criticalcss/1/)
Contains below the fold elements with `«display:none»` declaration, so such elements with all their css rules were kept in critical css (unwanted behavior). If you remove the `«display:none»` declaration — elemens will not be included in critical css. 

**Instance#2** 
URL: [http://odisseya.github.io/criticalcss/2/](http://odisseya.github.io/criticalcss/2/)
The lazyloading images with `«display:none»` (from whole page) are keeping in the critical css.

**Comment by futureweb** [comment]
Well ... I never touched Node before in my life ... but I think/hope/guess the PR should work ... more or less ... ;-)
https://github.com/pocketjoso/penthouse/pull/289

Unfortunately I was not able to test it as Test Env always failed with: "Cannot find module 'source-map' from 'source-map-support.js'"

**Comment by pocketjoso** [comment]
Available now in `penthouse@2.2.0`:
https://github.com/pocketjoso/penthouse/releases/tag/v2.2.0
