### ISSUE TITLE
Extract critical css from main css file?

### ISSUE THREAD

**Issue by ryanrussell** [pocketjoso/penthouse#246]
Is there a mechanism to save the original css file minus the critical css?

For example: 
Original CSS - 30kb
Critical CSS - 10kb
Defered CSS - 20kb

I didn't see anything in the src or docs to do this. Any suggestions are greatly appreciated!

**Comment by midzer** [comment]
You can use https://github.com/addyosmani/critical with `extract` parameter set to `true`

**Comment by ryanrussell** [comment]
great. thank you!

**Comment by pocketjoso** [comment]
⚠️ Note that this is a bad idea unless you only have 1 page on your whole site. Your full css is meant to be cached and re-used on future page visits, but by extracting the critical css you create unique full css version for every single page, so no re-use... So I strongly recommend against doing this.
