### ISSUE TITLE
Using penthouse with browser instance not working

### ISSUE THREAD

**Issue by hummal** [pocketjoso/penthouse#249]
I was testing around with using a puppeteer browser instance and I encountered some problems.

First of all, as I could see you do not expect an browser instance. It is a promise you expect to be there? Am I wrong?
After I used a promise of puppeteer.launch it was working till a point where I had trouble with 
`Cannot read property 'on' of undefined`
Undefined should be a browser page. But it was cleaned up before and also the browser was closed. 

As you can after generateCriticalCss the debug message "closed browser" appeared. Later on there is a new preparePage which result in an undefined page.

DEBUG LOG:
`penthouse:core page load DONE +4ms
  penthouse:core pruneNonCriticalSelectors done +7s
  penthouse:core AST cleanup START +1ms
  penthouse:core AST cleanup DONE +101ms
  penthouse:core generated CSS from AST +2ms
  penthouse:core generateCriticalCss DONE +0ms
  penthouse:core cleanupAndExit start +1ms
  penthouse:core cleanupAndExit -> try to close browser page +0ms
  penthouse:core cleanupAndExit end +2ms
  penthouse remove browser page for generateCriticalCss, now: 0 +21s
  penthouse generateCriticalCss done +0ms
  penthouse closed browser +28ms
  penthouse call generateCriticalCssWrapped +10ms
  penthouse adding browser page for generateCriticalCss, now: 1 +8ms
  penthouse:core Penthouse core start +46ms
  penthouse:core preparePage START +0ms
  penthouse:core parse ast START +1ms
  penthouse:core parse ast DONE (with 0 errors) +73ms
  penthouse:core unexpted: could not open browser pageError: not opened +1ms
  penthouse:core stripped out non matching media queries +3ms
  penthouse:core page load start +0ms`

So I guess you close the browser on finishing all the operations. Means if you got multiple tabs open you wait for them to finish and close the browser then. But if I would have my own browser and give it to penthouse, I guess I don't want it to be closed by penthouse. Because I propably had something to do with it before giving to penthouse. And maybe I want to use it later on again.

In my special case I want to track the time for 20 non concurrent tasks. But the browser I created before was closed after the first task and didn't exist after that. 

Am I wrong?

**Comment by pocketjoso** [comment]
Sorry for the late answer, and I know you're working on your own fork, but here's the info anyway:
By default Penthouse closes the browser as soon as it's idle. This info was missing in the example, I have now [updated it](https://github.com/pocketjoso/penthouse/blob/master/examples/custom-browser.js) to warn about this.

As the example says you can use the `unstableKeepBrowserAlive` option to opt out of Penthouse closing the browser for you.

I was thinking maybe it would be better for penthouse not to close the browser if the user passes it in, but I didn't want to make a change not knowing enough about how people use this option, so for now the behavior will stay like this.

I think this resolves your issue - but if it doesn't, please let me know and we'll reopen it again.
