### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. 

### ISSUE THREAD

**Issue by hummal** [pocketjoso/penthouse#250]
As the title describes it will throw that error if you use penthouse on more than 10 urls concurrently. 

index.js
`  process.on('exit', exitHandler)
  process.on('SIGTERM', exitHandler)
  process.on('SIGINT', exitHandler)`

These are the 3 handlers it gives a warning for. 
The easy way is to set maxEventHandlers to infinity, but I guess this is not the best option.

Iam not sure this is a real bug or this is just needed. But you should have a look at least.

**Comment by pocketjoso** [comment]
This is expected, and not a memory leak. Each call to Penthouse sets up it's own exit listeners.

You can ignore the warning, or bump the maxEventHandlers number.
