### ISSUE TITLE
loadPage return nothing but assigned a return value

### ISSUE THREAD

**Issue by hummal** [pocketjoso/penthouse#256]
In core.js "loadPage" is defined and do not return anything as the promises are resolved withing the function. 
https://github.com/pocketjoso/penthouse/blob/71467a2f7b15550d5a8e6834ddcfe3807d4c19da/src/core.js#L21
But later you are using loadPage to assign the return value (Expected promise) to a const. This const is used in a Promise.resolve which is a success. But only because Promise.resolve(undefined) is always resolved. 
https://github.com/pocketjoso/penthouse/blob/71467a2f7b15550d5a8e6834ddcfe3807d4c19da/src/core.js#L290
https://github.com/pocketjoso/penthouse/blob/71467a2f7b15550d5a8e6834ddcfe3807d4c19da/src/core.js#L303

**Comment by pocketjoso** [comment]
You are right, this code is wrong. I will fix it.

**Comment by pocketjoso** [comment]
OR let me check your PR first, maybe we can just fix it there since you are touching this code.

**Comment by pocketjoso** [comment]
Checked the code more closely - as it was an _async_ function it did return a Promise - as async functions automatically do. Regardless, the code is more clear as this function was used without this being an async function, so I pushed a commit to master with this change now.

**Comment by hummal** [comment]
so close this pr?

**Comment by pocketjoso** [comment]
Yep.
