### ISSUE TITLE
TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by dr0bz** [pocketjoso/penthouse#274]
Sometimes we are getting this error, when running penthouse:

`TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded`

It is not really reproducible. Sometimes we can run penthouse many times without failing. I assume the problem is the slow url we are running against. Therefore config contains following regarding timeouts:
```
timeout: 180000,
pageLoadSkipTimeout: 180000,
```
Not sure about the last one. Nevertheless ideas?

**Comment by pocketjoso** [comment]
Can you share the url?

Are you running a lot of `penthouse` jobs (calls) at the same time, or just one?

**Comment by dr0bz** [comment]
Hi @pocketjoso, it's our staging server which I cannot share. Sorry. The weird thing is, that running penthouse on my machine against the same url never throws this error. But running it on our deployment server fails from time to time with above timeout. I already made sure the node modules are the same on both machines.

I'm running it in the same [manner](https://github.com/pocketjoso/penthouse/blob/master/examples/many-urls.js) but synchronously. One at a time. Simplified code:

```
grunt.registerMultiTask('extract_critical_css', 'Extract critical css', function(){
        var pageConfig = {
            home: 'https://home',
            search: 'https://search'
        };
        var penthouseOptions = {
            width: 1450,
            height: 900,
            timeout: 180000,
            pageLoadSkipTimeout: 180000
        };
        var criticalCssPath = './criticalCss/';
        var pageNames = Object.keys(pageConfig);
        var done = this.async();

        function startExtracting() {
            if (pageNames.length === 0) {
                return Promise.resolve();
            }

            var pageName = pageNames.pop();
            var url = pageConfig[pageName];
            penthouseOptions.url = url;
            penthouseOptions.css = './css/' + pageName + '.css';

            return penthouse(penthouseOptions).then(function(criticalCss){
                    var outputFile = criticalCssPath + pageName + '.css';
                    grunt.file.write(outputFile, criticalCss);

                    return startExtracting();
                });
        }

        startExtracting()
            .then(function() {
                done();
            }).catch(function(err) {
                done(false);
            });
    });
```

**Comment by pocketjoso** [comment]
I can't see anything suspicious here. Could you run your command with
environment variable:
`DEBUG="penthouse,penthouse:core"`

So if you call your gull task from yhe command line, something like:
`DEBUG="penthouse,penthouse:core" gulp`

Then if you share the debug output we can learn a bit more.

Other than that, the only thing I see is that you seem to be passing
different css to different pages. Maybe it's just incorret in the
simplified code you shared, but generally your full css (passed to
penthouse) would be he same for all your pages. You can also speed up your
penthouse execution a bit by reading the contents of your css file into a
string before calling penthouse, and then passing it via the `cssString`
option instead.

Le jeu. 27 sept. 2018 09:05, Hermann Bier <notifications@github.com> a
écrit :

**Comment by dr0bz** [comment]
Here is the debug output:
```
  penthouse call generateCriticalCssWrapped +0ms
  penthouse:core Penthouse core start +0ms
  penthouse:core parse ast START +2ms
  penthouse:core parse ast DONE (with 10 errors) +86ms
  penthouse:core stripped out non matching media queries +20ms
  penthouse:core open page ready in browser +20ms
  penthouse:core userAgent set +2ms
  penthouse:core preparePage DONE +1ms
  penthouse:core page load start +0ms
  penthouse:core turn css to formatted selectorlist START +3ms
  penthouse:core turn css to formatted selectorlist DONE +79ms
  penthouse:core cleanupAndExit +30s
 -- TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
```

Regarding different css files: that's fine. We are having separate css files for critical pages to minimize file size. But thanks for the tip regarding `cssString` option.

**Comment by pocketjoso** [comment]
All right .So the page load event never happens for your site in this log
output. What version of penthouse are you on? Can you try on the latest
version?

Le jeu. 27 sept. 2018 16:46, Hermann Bier <notifications@github.com> a
écrit :

**Comment by dr0bz** [comment]
The version is 1.8.2. Are you sure regarding 
> never happens

?
Or is the load event just not occurring under 30000ms? This is really possible.

**Comment by pocketjoso** [comment]
It's possible that the load fires later, but not very likely. Can you try a
few different pages, also some from a completely different site, and see
which case(s) trigger this behavior for you?

Le jeu. 27 sept. 2018 17:16, Hermann Bier <notifications@github.com> a
écrit :

**Comment by dr0bz** [comment]
I have good news - I could reproduce the error. I prepared an environment where you can reproduce it your self: https://github.com/dr0bz/penthouse-274-issue. What I've found out: 
- if the load event triggers aftert 30s - penthouse throws a timeout error.
- after setting the config option`timeout` to more than 30s - than puppeteer will throw a timeout error.

**Comment by dr0bz** [comment]
@pocketjoso thank you very much for your fast response und the fix! The slow speed of our staging system is a known issue :)
