### ISSUE TITLE
Make this usable with Chrome

### ISSUE THREAD

**Issue by tandrewnichols** [pocketjoso/penthouse#278]
Chrome has it's own headless mode now, so it's redundant to download Chromium. I realize that happens as part of the puppeteer install and not here and that there's a way around that via `puppeteer.getBrowser` in the options to penthouse, but in my experience, that workaround doesn't actually work (I'm using the example in `examples/custom-browser` exactly as is but with `executablePath` pointing to the Chrome app). It always fails with ` UnhandledPromiseRejectionWarning: Error: Protocol error (Target.createTarget): Target closed.` Puppeteer has [this issue](https://github.com/GoogleChrome/puppeteer/issues/1947) related to that which suggests that the problem is `browser.close()` in `lib/browser.js` should be `await browser.close()`. Or maybe `browser.close().then` since the function it's defined in doesn't use the `async` keyword.

I think ideally this library would default to using Chrome first cause a lot of people already have that, but if that's not a direction you want to go, I'd at least like the workaround to work.

Thanks!

**Comment by pocketjoso** [comment]
Hi,

I didn't think about this before. In theory the custom-browser example should just work when using `executablePath`, but I also came across an issue when I tried it with my local chrome (`69.0.3497.100`, on MacOS). For me, `google.com never loaded, so I always had timeout errors (does not happen with chromium). When I switched to another url, it worked.. Not sure why.

This highlight an issue. As puppeteer states in their documentation, they might rely on features that haven't yet made it from Chromium to Chrome, so some weirdness can be expected.

Did you try with more different urls; do you have the same error in all cases? What version of Chrome did you try running?

**Comment by pocketjoso** [comment]
Upgraded to latest Chrome (`70.0.3538.77`) and now it works for me with `google.com` as well.

Already with this in mind it seems to me to be a bad idea to change the defaults from running Chromium, as long as Puppeteer is used. It could still be documented as an example, with the right warnings.

First let's explore your issues a bit. By what you described it sounds like the first critical css generation works, but the second does not - is that the case? What does your penthouse call look like; what other options are you using?

**Comment by pocketjoso** [comment]
Okay, I've found a race condition issue running back-to-back penthouse calls. It doesn't have anything to do with using a custom browser, but I think it's the issue you have come across here. I will look for a fix and get back to you.

**Comment by pocketjoso** [comment]
Pushed a fix in https://github.com/pocketjoso/penthouse/pull/279, @tandrewnichols could you please install:
`penthouse@1.10.1-rc`

and try again and see if it fixes your issue?

**Comment by tandrewnichols** [comment]
Yes, I'll check it out. FWIW, I'm on Chrome 70.0.3538.77 and it _is_ on the second page that I see that error. We generate different critical css for maybe 8 pages using async (the module, not the keyword), but we use `eachSeries`, so it should be closing the previous one before moving on. These are all localhost routes.

**Comment by tandrewnichols** [comment]
Just tried it. The first page still succeeds, but on the second, I get `Error: net::ERR_EMPTY_RESPONSE`.

**Comment by tandrewnichols** [comment]
Here's the whole stack in case that's helpful:

```
Error: net::ERR_EMPTY_RESPONSE at http://localhost:8000/howto?ftoggle-frontend-development-on=abTests.navbar.nav_all_new,speed.noCssPreload
  at navigate (/Users/andrewnichols/code/anichols/manta/manta-frontend/node_modules/puppeteer/lib/FrameManager.js:103:37)
  at <anonymous>:null:null
  at process._tickCallback (internal/process/next_tick.js:182:7)

  -- ASYNC --
  at Frame.<anonymous> (/Users/andrewnichols/code/anichols/manta/manta-frontend/node_modules/puppeteer/lib/helper.js:144:27)
  at Page.goto (/Users/andrewnichols/code/anichols/manta/manta-frontend/node_modules/puppeteer/lib/Page.js:579:49)
  at Page.<anonymous> (/Users/andrewnichols/code/anichols/manta/manta-frontend/node_modules/puppeteer/lib/helper.js:145:23)
  at loadPage (/Users/andrewnichols/code/anichols/manta/manta-frontend/node_modules/penthouse/lib/core.js:494:30)
  at /Users/andrewnichols/code/anichols/manta/manta-frontend/node_modules/penthouse/lib/core.js:308:33
  at Generator.next (<anonymous>:null:null)
  at step (/Users/andrewnichols/code/anichols/manta/manta-frontend/node_modules/penthouse/lib/core.js:475:191)
  at /Users/andrewnichols/code/anichols/manta/manta-frontend/node_modules/penthouse/lib/core.js:475:361
  at <anonymous>:null:null
  at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by tandrewnichols** [comment]
Ok, you're right on that one. The server was restarting after each url because of our watch task, which I never noticed when running with Phantom because it took so long the server had time to restart. Once I started ignoring the generated files, everything went smoothly. Thanks for debugging with me! And thanks for the _significantly_ improved speed!

**Comment by pocketjoso** [comment]
All good! Consider running the tasks in parallel as in the many urls example I linked to to increase speed more. :)

**Comment by tandrewnichols** [comment]
Thanks, I'll give it a try.

**Comment by tandrewnichols** [comment]
I get MaxListenersExceededWarning when I run those in parallel. Is that unexpected?

```
(node:44297) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:44297) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
(node:44297) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:44297) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Symbol(Connection.Events.Disconnected) listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by tandrewnichols** [comment]
Ah, I just now saw the comment in the many-urls example:

```
 If you need to run many pages however your machine will at some point
// (~ 10 pages) start running out of resources (causing crashes, errors and/or slowdown).
```

I'll queue them up differently.

**Comment by pocketjoso** [comment]
it's automatic that you get such warnings after having 10 or more penthouse processes in parallel (or any other node process that sets up event listeners). It's just a warning - penthouse does not have any memory leaks and cleans up after itself. In this regard you can run more than 10 processes in parallel - however as you said this might slow down your machine anyway. I usually stay under 10 for this reason. 👍
