### ISSUE TITLE
Is it possible to write non critical css with penthouse?

### ISSUE THREAD

**Issue by skulden13** [pocketjoso/penthouse#281]
Hi @pocketjoso,

I'm using your `penthouse` lib. It's a great tool!
But, what about a non-critical part of CSS? Is there a quick way to output it too into a separate file using the plugin output?

Here what I mean:
```
const penthouse = require('penthouse')
const fs = require('fs')

penthouse({
  url: 'https://google.com',
  cssString: 'body { color: red }'
})
  .then(criticalCss, nonCriticalCss => {
    // use the critical css
    fs.writeFileSync('critical.css', criticalCss)
    fs.writeFileSync('non-critical.css', nonCriticalCss)
  })
```

Thanks, Denis

**Comment by pocketjoso** [comment]
This is counterintuitive, but creating non critical css actually degrades performance. You can find more detail in my previous answer here:
https://github.com/pocketjoso/penthouse/issues/117#issuecomment-202744247

Closing as a duplicate.

**Comment by skulden13** [comment]
Ah, ok, sorry for duplicating.
Thanks!
