### ISSUE TITLE
CSS instead of PAGE_UNLOADED_DURING_EXECUTION

### ISSUE THREAD

**Issue by bezoerb** [pocketjoso/penthouse#282]
Hey once again :)

after your big help on #280 i thought you might also have an idea for this issue:
https://ci.appveyor.com/project/addyosmani/critical/builds/20435273/job/49apkroqyhecbbmx

The problem is that sometimes the [testfile](https://github.com/addyosmani/critical/blob/master/test/fixtures/issue-314.html) produces critical css even if there's no linked stylesheet and a `<meta http-equiv="refresh" content="0; url=https://example.com/">` tag inside. 

The expected result would be an error as described in #263.

**Comment by pocketjoso** [comment]
Super late reply - I completely missed this issue 🤦.

Is it still something that happens on your end?

**Comment by bezoerb** [comment]
Hey :)
