### ISSUE TITLE
No error on a 401 response caused by failed basic http auth.

### ISSUE THREAD

**Issue by dr0bz** [pocketjoso/penthouse#284]
Hello @pocketjoso ,

penthouse is not throwing an error if the server responds with 401. Penthouse is running against a basic http auth protected url. If the credentials in the url (https://foo:bar@www.example.com) are wrong or just missing - penthouse is not throwing an error and completes successfully.

Penthouse version: 1.10.2

Here is an example of a basic auth protected url for testing: 

http://www.httpwatch.com/httpgallery/authentication/authenticatedimage/default.aspx?0.7349707232788205

Credentials: httpwatch:whatever

Best regards

**Comment by pocketjoso** [comment]
All right, thanks for the bug report. If you have time, feel free to take a look at opening up a PR with a fix with this. If so, just let me know when you start working on it too - so we can avoid double work. Otherwise I'll get around to it eventually.

**Comment by dr0bz** [comment]
Hey @pocketjoso ,

fine, i'm looking into. Perhaps I can solve it.

Regards

**Comment by dr0bz** [comment]
Thank you for the support!

**Comment by dr0bz** [comment]
Do you plan to make a new release? I would like to use the new feature directly.

Regards,
dr0bz

**Comment by pocketjoso** [comment]
Released as `penthouse@2.1.0`. Will write release notes later, but this is the only change.

**Comment by dr0bz** [comment]
Thank you!
