### ISSUE TITLE
CLI progress when processing multiple URLs

### ISSUE THREAD

**Issue by pocketjoso** [pocketjoso/penthouse#29]
**This relates to the `dev` branch, where multi url critical css generation is possible.**

Currently there's no feedback given - if processing the multiple URLs will take 2 minutes, then the command line (or alike) will be completely blank during this time. In addition, it will be blank when `Penthouse` finishes.

My suggestion is that we just log something like `generated Critical-1.css (for "http://google.com")` each time we finish generating one url of a multi url job. 

(For bonus points we could also log the timing for each job, and do fancy color coding like `mocha` does.)

**Comment by fatso83** [comment]
Any reason this is open still? Seems resolved to me (as a kind of #wont-fix)

**Comment by pocketjoso** [comment]
I still want some progress when the command is run; if you're saying it's a no go for a Node module, then at least for the standalone version.

So would the idea be then to conditionally add log statements when in standalone mode?

**Comment by fatso83** [comment]
Ref #41?

**Comment by pocketjoso** [comment]
Yep.
