### ISSUE TITLE
Plugin is not considering the js files inclusion

### ISSUE THREAD

**Issue by kamalendugarai** [pocketjoso/penthouse#315]
This is working as expected except the javscript files webpack building are not including in the generated html files like html-webpack-plugin does, I have tried to use this plugin with html-webpack-plugin but it seems this plugin is overriding html-webpack-plugins functionality.

**Comment by pocketjoso** [comment]
Hi, which plugin are you talking about? Penthouse is not touching your html or javascript. Can you copy the code you are using to run?

**Comment by kamalendugarai** [comment]
Thank you! It was not this plugin what causing the issue.
