### ISSUE TITLE
What is CSSstring

### ISSUE THREAD

**Issue by datapolitical** [pocketjoso/penthouse#335]
I've tried googling it, but I can't understand what the point of CSSstring is. Don't I want to get *all* the css on the site, what's the point of passing the program a single css selector? what does it do?

Thanks!

**Comment by pocketjoso** [comment]
`cssString` is documented in the readme:
> Original css to extract critical css from

When using penthouse you either use this to pass in your original css as a string, or you can use the `css` file path option instead, if you have your original css saved on your file system.

**Comment by datapolitical** [comment]
Yes I saw it documented, I didn’t understand the documentation. So CSSString is your entire css as a single string, and css is the directory where your css files live?

How do you handle scss?

**Comment by pocketjoso** [comment]
> So CSSString is your entire css as a single string

Yes.

> and css is the directory where your css files live?

No, it's the file path to a single CSS file, containing all your CSS. So if you have multiple CSS files you need merge them first, either to a single file, or to a string (via JS).

> How do you handle scss?

Penthouse does not handle scss, you need to give it the final CSS - the one you are going to serve in your HTML (browsers also do not understand scss).

**Comment by datapolitical** [comment]
Can it handle media queries?

**Comment by pocketjoso** [comment]
Yes, it handles anything that a browser understands (from a CSS file) - including media queries.

> When I gave it my site URL I got css without the media queries.

Are you sure the CSS you provided to penthouse contained the media queries? Penthouse should only remove media queries that had no matching critical css inside them, or that targeted really large screens, or media not used on the web (like print media queries).
