### ISSUE TITLE
Chrome processes

### ISSUE THREAD

**Issue by mattlaue** [pocketjoso/penthouse#337]
I'm running penthouse from a route in express JS, thus creating a little micro-service to generate critical CSS.

Even when I limit it to one request at a time I still see multiple heavy chrome processes sitting around.  I would expect only 1-2 processes at a time: maybe one main process and one for the tab.

Is this expected behavior?  Can this be limited in any way?

**Comment by pocketjoso** [comment]
How are you calling penthouse? 

> I would expect only 1-2 processes at a time: maybe one main process and one for the tab.

With the default penthouse settings my expectations would be the same.

Can you see what the names of the heavy chrome processes are?

**Comment by mattlaue** [comment]
These processes are from running penthouse on a single URL (basically the google.com example from the docs)

```
root      182485  0.0  2.1 413880 87224 ?        Ssl  14:11   0:00 /app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --disable-setuid-sandbox --no-sandbox --ignore-certificate-errors --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_chrome_profile-agZfAX
root      182490  0.0  1.1 261056 48132 ?        S    14:11   0:00 /app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome --type=zygote --no-sandbox --headless --headless
root      182506  0.0  1.7 311512 70800 ?        Sl   14:11   0:00 /app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome --type=gpu-process --field-trial-handle=759329575002737336,6194848084648503412,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=TranslateUI --no-sandbox --disable-breakpad --headless --headless --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --override-use-software-gl-for-tests --shared-files
root      182508  0.0  2.5 4559168 102848 ?      Sl   14:11   0:00 /app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome --type=renderer --no-sandbox --allow-pre-commit-input --disable-background-timer-throttling --disable-breakpad --enable-automation --file-url-path-alias=/gen=/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/gen --force-color
```

These are running inside a Docker container (which is why they appear as root).

Also I just noticed when collecting the above that there are a lot of defunct Chrome processes left over.

`root      182317  0.0  0.0      0     0 ?        Z    14:11   0:00 [chrome] <defunct>`

**Comment by pocketjoso** [comment]
Double checking on my end I have the same number of processes, when running on Linux:
- 1 "main window" (I think)
- 1 `type=renderer` per open tab (depending on your Penthouse settings)
- 1 `type=gpu-process`
- 1 `type=zygote`

So this is normal then, for Penthouse.

I do believe all these processes are spun up by Puppeteer, or even Chromium directly. I'm not sure whether this is something that could be handled differently.

> Also I just noticed when collecting the above that there are a lot of defunct Chrome processes left over.
> root 182317 0.0 0.0 0 0 ? Z 14:11 0:00 [chrome] <defunct>

What are you doing exactly when "collecting"?

I doubt that I would know much to answer what's happening here though - I think it's on a lower layer. I would ask in the [puppeteer lib](https://github.com/puppeteer/puppeteer) about this.

**Comment by mattlaue** [comment]
By 'collection', I just meant that I saw the defunct processes when I ran one of the scripts from the documentation in order to list what processes were created.

I'll close this now.
