### ISSUE TITLE
Missing styles

### ISSUE THREAD

**Issue by bezoerb** [pocketjoso/penthouse#37]
Hey @pocketjoso,

our tests for `critical` and `grunt-critical` are failing since your last release (0.2.52)
With 0.2.51 everything works fine.
I've created a gist with the resulting css before and after the version bump:
https://gist.github.com/bezoerb/04aa464eeecead2f7b0b

**Comment by pocketjoso** [comment]
Thanks, sorry about this. Will sort out as soon as I find some time, hopefully tonight.

**Comment by pocketjoso** [comment]
@bezoerb Sorry for delay, now resolved by #38 .

**Comment by bezoerb** [comment]
@pocketjoso thanks!
