### ISSUE TITLE
Flag for writing output to stdout

### ISSUE THREAD

**Issue by pocketjoso** [pocketjoso/penthouse#40]
As the next version of Penthouse moves to saving the generated CSS to file(s), necessary when generating for  multiple urls at the same time, I believe that it's necessary for us to maintain a way to output directly to stdout. This would obviously only be possible when critical css for a single url is requested.

This allows chained calls using Penthouse, as in [Critical](https://github.com/addyosmani/critical/blob/master/src/critical.js#L177), gulp(?), and in other places. Writing to file is not always what you want, let's not break useful patterns while moving forward.

Not sure what the flag should be, since we're kind of doing `-w` by default... I'll think about it, let me know if you have a suggestion.

**Comment by fatso83** [comment]
Not sure what you mean by -w? Write to file? 

If the command can specify the output file name, it is quite normal to specify writing to stdout by using a dash as the filename ("-"), but as we don't support output file naming, I think a better approach is just to have a "-O" option that dumps the output to stdout and errs out if the user specifies more than one url.

**Comment by pocketjoso** [comment]
> "-O" option that dumps the output to stdout and errs out if the user specifies more than one url.

Sounds good to me.

**Comment by fatso83** [comment]
Closing?

**Comment by pocketjoso** [comment]
Yep.
