### ISSUE TITLE
Proposal: simple tools - more powerful Node module

### ISSUE THREAD

**Issue by fatso83** [pocketjoso/penthouse#41]
I have been thinking a lot about how we can do the following better without complicating things too much 

1. process multiple files
2. keep the simple semantics of outputting the file to stdout
3. keep the PhantomJS core simple

The goals of #1 and #2 are in conflict as it is (see #40), and the semantics become messy to the end user. I have been thinking of fifos and event architectures without really getting anywhere, but what I propose is the following, which might seem radical, but to me is a simplification for the better (compared to the dev branch).

# Keep end user tools simple
- Stick to the way it works today: only process one url in the penthouse tool.
- Maybe change the options parsing somewhat to support various options (like in the dev branch), but still limit to processing one url

# Do hard stuff in the node module
I am guessing 9/10 uses of a multiple url supporting version will be driven by a script of some type, and therefore I think it is reasonable to restrict the user land tools to just accept one url per run.

This could prove to have some interesting effects.
- We could speed up processing of multiple files through parallelization using a [cluster of background instances](https://github.com/dailymuse/phantom-cluster)
- We could keep the existing API without any changes
- To process multiple files you call the penthouse function multiple times, as today, but the response should be quicker

**Comment by fatso83** [comment]
... and most of the open issues today could be closed. Would of course cherry pick some of the work in the dev branch.

**Comment by pocketjoso** [comment]
It's something that worried me from the start, that the multiple url processing (and especially writing to file by default) would make the core tool harder to use.

How could `Penthouse` make use of something like `clustered PhantomJS instances` - if each the calls for each url were made separately?

**Comment by pocketjoso** [comment]
If we were to drop the multi url handling in the `dev` branch in the end, I would still cherry pick the modularisation, and the standalone build scripts you wrote.

**Comment by fatso83** [comment]
Re the cluster question: the node module would on import/`require`  spin up the instances in the background. Each subsequent call to penthouse would then be handed off to a new (or reused) instance.

**Comment by pocketjoso** [comment]
Let's try that out. This weekend Ill start cleaning up a new dev branch without the multi URL API (but I'll save this branch as multi-URL or so).

**Comment by fatso83** [comment]
Turns out this wasn't so easy after all ... Using the cluster module requires you to basically write the Phantom script as part of a node module ([see PhantomJS docs](https://github.com/sgentle/phantomjs-node)), adhering to the differences of that way of doing things. 

Keeping the same code for both the standalone and the node module would then be hard (impossible?), but I think we could circumvent this by an additional build step for the Node module that exchanges some bits of code for the `phantomjs`-module equivalent.

Example:
```
	page.viewportSize = {
		width: options.width,
		height: options.height
	};

page.onCallback = function() { ... }
``` 
would be swapped for 
```
	page.set('viewportSize',  {
		width: options.width,
		height: options.height
	});

        page.set('onCallback', function() { ... })
```

This is not impossible, but requires a bit of tinkering to get the concatenation going, as well as quite a bit of restructering (that might not seem to make sense for the casual reader), so I'll leave the clustering bit for later.

**Comment by fatso83** [comment]
Closing this now, and will rather submit a PR later on when I get the chance.
