### ISSUE TITLE
Only Optimised for desktop (not mobile)

### ISSUE THREAD

**Issue by IsmailM** [pocketjoso/penthouse#42]
I think this is only optimised for desktop browsers and not mobiles...

Take a look at this website: [http://mazion.co.uk](http://mazion.co.uk) on a mobile, especially the navbar...

**Comment by pocketjoso** [comment]
By default `Penthouse` generates css for a screen sized `1300x900`. You can chose to generate the css for [different dimensions](https://github.com/pocketjoso/penthouse#optional-parameters).

**Comment by IsmailM** [comment]
I ended up temporarily inlining the full CSS due to another problem, which meant that a sub page wouldn't load properly when using critical CSS...

I am now using the Critical CSS that you generated but I still have this same problem - As such I have created a Stackoverflow Post on it (see [here] ( http://stackoverflow.com/questions/28289634/when-using-critical-css-jquery-function-does-is-not-running-on-load))

Many Thanks for all your help

**Comment by pocketjoso** [comment]
@IsmailM: I hope you are aware that the generated critical css is specific for *one* page (the one I gave you; for the front page) - and that you can're-use the same critical css for sub pages..

**Comment by IsmailM** [comment]
Thanks for letting me know. I think this may be the problem - Is it possible to merge the critical CSS of two pages together?...

**Comment by pocketjoso** [comment]
@IsmailM First of all I want to say that if you were to combine multiple critical css files you would start losing the benefit of using critical path css. If you can't generate and inline critical css for every page individually, I would recommend focusing on your top landing page(s), generating and inlining critical css there, and worry less about the rest of your pages.

If you really want to go down the combination route, I'm sure there are some tools you can find online for that purpose. I haven't used any of them though, so I can't make any recommendations.
