### ISSUE TITLE
Online Penthouse fails with some HTTPS websites (SNI)

### ISSUE THREAD

**Issue by tkrotoff** [pocketjoso/penthouse#49]
My website (https://osteo15.com) fails with http://jonassebastianohlsson.com/criticalpathcssgenerator/:
`There was a problem generating our critical path CSS. Check your URL, or try again later.`

Might be due to [Server Name Indication (SNI)] (https://en.wikipedia.org/wiki/Server_Name_Indication#No_support) (https://osteo15.com uses SNI).

When I try with another https website, for example https://html5.validator.nu/ => no problem.

**Comment by pocketjoso** [comment]
Thanks for reporting this issue. I have seen some HTTPS sites fail, I will see what can be done about that.

**Comment by pocketjoso** [comment]
Looked into it a bit more and it's `phantomjs` that fails to connect to your site, but only when running on a `linux` platform (such as my web server). Would be keen to see if the new `2.0.0` version if `phantomjs` resolves this issue, but binaries for linux haven't been released yet.

Will continue looking for a solution during the weekend.

**Comment by pocketjoso** [comment]
Can't find any solution for Linux, don't quite know where to look.

@tkrotoff : What I suggest for you if you're still looking for a solution, either one of these things:
1. Check that you have TLS 1.0 turned on on your server (long shot, based on [this old thread](https://code.google.com/p/chromium/issues/detail?id=114943#c9))
2. Generate your critical css using the command line tool, or grunt if you use that.
3. If it's just for one or two or so pages, give them to me and I can do step 2 for you and hand you the result.
4. Wait for Linux binaries for phantomjs 2.0.0.

Sorry for not being able to help more than this!

**Comment by tkrotoff** [comment]
I'm using Amazon S3 and CloudFront, Chrome says the connection uses TLS 1.2.
Thanks for your help, i'm not in hurry: I will just wait for the online site to be fixed. Please let this ticket open meanwhile so I will get the notification.

I guess your Linux server uses [Qt < 4.8](https://bugreports.qt.io/browse/QTBUG-1352). PhantomJS is based on Qt, version 2 uses Qt 5.

**Comment by pocketjoso** [comment]
Now using 2.0.0 binaries - and SNI sites seem to work! :) @tkrotoff Let me know if you still see any issues.

**Comment by tkrotoff** [comment]
It works fine now, thanks!

**Comment by puccamandora** [comment]
Hi, i'm having a same problem with http://jonassebastianohlsson.com/criticalpathcssgenerator/. 
when I generate critical CSS. can anybody help with this?
