### ISSUE TITLE
"@-moz-document" can't be passed by "penthouse"

### ISSUE THREAD

**Issue by voku** [pocketjoso/penthouse#50]
Warning: css/critical-path.css:834:32: Unexpected } Use --force to continue.

```
@-moz-document url-prefix() {
  .portal-select {
    overflow: hidden; }

  .portal-select select {
    width: 120%;
    width: -webkit-calc(100% + 3em);
    width: -moz-calc(100% + 3em);
    width: calc(100% + 3em); } }
```

... will be converted into ...

```
  .portal-select select {
    width: 120%;
    width: -webkit-calc(100% + 3em);
    width: -moz-calc(100% + 3em);
    width: calc(100% + 3em); } }
```

**Comment by pocketjoso** [comment]
Thanks for reporting this issue, will fix this weekend.

**Comment by pocketjoso** [comment]
[Firefox actually seems to support @document without the browser prefix now](https://developer.mozilla.org/en-US/docs/Web/CSS/@document#Browser_compatibility). I'll add it in anyway so it doesn't break for people.

**Comment by pocketjoso** [comment]
Resolved in `Penthouse 0.3.1`, via #51.

**Comment by voku** [comment]
Thanks for the fix and have a nice (rest of the) weekend! ;)

**Comment by pocketjoso** [comment]
You too!

**Comment by voku** [comment]
hi, can your update the version-tag? --> from "0.3.1" to "v0.3.1" ?

**Comment by pocketjoso** [comment]
Done.

**Comment by voku** [comment]
thx :)
