### ISSUE TITLE
Options to force include / exclude selectors

### ISSUE THREAD

**Issue by gionkunz** [pocketjoso/penthouse#52]
Hi there. Great library, I'm using it for some time now in various projects. I wanted to ask if there are any options to specify selectors to be forced for inclusion / exclusion. This would be very helpful for various cases. 

By default hidden elements (display: none) don't get into the CSSOM and I guess penthouse is not even considering them to include. However, if you work with CSS classes to toggle visibility and the initial state on a landing page is hidden (by a selector `.my-page .hidden` for example) I'd like to include this style in the critical output. This is important as invisible content will be visible until the full CSS is loaded async.

The same could be done with a selector list called exclude and if you don't want to include minor stylings that don't affect layout so much in this list.

One additional idea would be to have an option to substitute the excludes that allows you to configure some CSS attributes in an object / string. This is particularly interesting if you'd want to substitute some elements on your page with `display: none` or `visibility: hidden` until the full CSS is loaded async.

I thought of a config like this:
```javascript
include: [
  '.page-content > li:last-child',
  '.error-message'
],
exclude: [
  '.huge-hero-banner',
  '.unimportant-styles-on-images'
]
```

Or together with exclude substitution:

```javascript
include: [
  '.page-content > li:last-child',
  '.error-message'
],
exclude: {
  '.huge-hero-banner': {
    visibility: 'hidden',
    height: '50vh'
  },
  '.unimportant-styles-on-images': {
    display: 'none'
  }
}
```

What do you think?

**Comment by pocketjoso** [comment]
Hi, thanks and I'm glad you like `Penthouse`. I'm going to read through and give you a proper response tomorrow. If this feature highlights a common enough use case I'll consider adding it in.

**Comment by pocketjoso** [comment]
@gionkunz Sorry for the long delay to my response.

> By default hidden elements (display: none) don't get into the CSSOM and I guess penthouse is not even considering them to include.

Penthouse doesn't use the CSSOM. Any element that is styled with `display: none` **will** be included in the critical CSS. It would be safe to remove rules that involved `display: none` that applied to elements below the fold - but Penthouse doesn't do checks like that at the moment.

---

Do you have any other use cases for your suggested `include` and `exclude` features?

**Comment by pocketjoso** [comment]
No response so will close - will reopen if I get new info that showcases the need for this feature.

**Comment by gionkunz** [comment]
Hey there. Sorry somehow  I missed to answer :( Actually I also figured you're not excluding styles above the fold with `display: none` and this kind of destroys the use-case I had in mind. It looks like it's more a crazy idea I had in that moment which turned out to be not so usable :-)

Cheers
Gion

**Comment by pocketjoso** [comment]
No problem, thanks for creating replying and for creating the issue in the first place! :)
