### ISSUE TITLE
Broken CSS returned when used with large CSS Files

### ISSUE THREAD

**Issue by darkspotinthecorner** [pocketjoso/penthouse#54]
Hi there, great lib. Thanks a lot for this! :)

However, I managed to get reproduceable broken output when using penthouse with large css file bases.

Just run the following through your [online tool](http://jonassebastianohlsson.com/criticalpathcssgenerator/):
1. URL: http://www.pferd.de/forums/386-westernreitweise
2. CSS: [Contents of this link](http://c.fhcdn.net/www.pferd.de/css.php;styleid=11&langid=2&d=1428924935&td=ltr&embed=1&sheet=bbcode.css,editor.css,popupmenu.css,reset-fonts.css,vbulletin.css,vbulletin-chrome.css,vbulletin-formcontrols.css,ffnewsletter_widget_guestsubscribe.css,fhtys_block.css,widgets.css,tagcloud.css,sidebar.css,ffsidebar.css,ffblocks_block_html.css,ffblocks_block_ffadvert.css,ffblocks_block_ffadvert.css,ffblocks_block_cmsarticles.css,ffblocks_block_mpfilters.css,ffblocks_block_ffnewsletter_guestsubscribe.css,ffblocks_block_fhtys_poll.css,ffblocks_block_welcome.css,ffblocks_block_buddyonline.css,ffblocks_block_chatuseronline.css,ffblocks_block_socialbuttons.css,ffblocks_block_ffadvert.css,ffblocks_block_tagcloud.css,ffblocks_block_ffadvert.css,marketplace_navbar_tab.css,fflayout_offscreennav.css,relevant_replacements.css,forumhome_sub_forum_manager.css,advertising.css,toolsmenu.css,forumbits.css,forumdisplay.css,threadlist.css,options.css,fh_layout.css,fh_layout_sub.css,fh_layout_subsub.css,additional.css,responsive.css,responsive_forumdisplay.css,fhquickpost.css&nooptimize=1)

When you paste the resulting CSS into the [W3C CSS Validator](https://jigsaw.w3.org/css-validator/#validate_by_input) you will recognize unclosed rule blocks that will result in parse errors. The original CSS however seems to be "fine" at those specific places.

If I separate those offending blocks and run them alone against penthouse, the generated css is fine. The issue only appears when penthouse is dealing with large files.

**Comment by pocketjoso** [comment]
Hi, thanks for reporting this issue. I'm a bit short on time right now, I'm hoping to be able to look into this during the next weekend.

Cheers

**Comment by pocketjoso** [comment]
@darkspotinthecorner I'm looking at this now and I can't quite tell what particular broken output that it is you say `Penthouse` is responsible for. There are quite a few parse errors in your original css...

Can you give me a specific example of a rule that is correct before, and broken after (running Penthouse)?

**Comment by darkspotinthecorner** [comment]
I'll try to find a more compact example tomorrow. Thanks for looking into this. :)
