### ISSUE TITLE
Making this work on server

### ISSUE THREAD

**Issue by linnett** [pocketjoso/penthouse#56]
Hi, 

Can someone please give me some advice on how this can work on a server when the Gulp file is being run to build the site? 

Thanks,

Sam

**Comment by pocketjoso** [comment]
Sam,

Check out the [node module example](https://github.com/pocketjoso/penthouse/blob/master/README.md#as-a-node-module). Let me know if you need any more help.

Cheers

**Comment by pocketjoso** [comment]
Or did you mean how to serve the critical css?

**Comment by linnett** [comment]
It's the URL part I need some assistance with. When working locally, I can just use my localhost to where I'm working so the criticalCSS works fine. But when this gets compiled on the server, it doesn't know how to resolve the localhost because obviously that's only relevant to me locally. I wondered how people got around that issue. Is there a service I can run on the server to make it work? Or will I have to compile the crtical CSS and commit that to the server rather than running it on a production build? Thanks

**Comment by pocketjoso** [comment]
Something I haven't documented properly that might help you is that you can pass in a html file instead of a URL to Penthouse.

Does that get you further?

**Comment by linnett** [comment]
Ah OK. Can I pass a group of HTML files using a wildcard (*) or do I have to name them all separately?

**Comment by pocketjoso** [comment]
> Ah OK. Can I pass a group of HTML files using a wildcard (*) or do I have to name them all separately?

You have to make several calls to `penthouse`, one per html file.
```
var css = 'styles/main.css';
[ 'http://google.com', 'http://github.com', 'http://codepen.io' ].map(function(url){
  penthouse({
      url : url,
      css : css,
      width : 1300,   // viewport width
      height : 900   // viewport height
  }, function(err, criticalCss) {
      console.log(criticalCss);
  });
});
```

-- 
For the future: perhaps `Penthouse` could accept an array and process them one by one (or partially in parallel), could be a nice feature. Something we've worked on before but that never shipped.

**Comment by pocketjoso** [comment]
Also note two things about calling Penthouse like in the example above:

* The callbacks are async; you need wrap the penthouse call in an IIFE or similar to get access to the `url` corresponding the the `criticalCss` by the time of the callback
* Don't make too many calls to `Penthouse` at the same time. In current implementation each call will just fire up another `PhantomJS` instance, and they will eventually consume the full CPU and calls will start to timeout and/or crash.

I never got enough interest in executing `Penthouse` this way... but looking at it now it should really handle this much better. Will fix in future.

**Comment by linnett** [comment]
Thanks for the help with this !! :)

**Comment by pocketjoso** [comment]
No problem. :)

**Comment by peyman-mohamadpour** [comment]
> Sam,
> 
> Check out the [node module example](https://github.com/pocketjoso/penthouse/blob/master/README.md#as-a-node-module). Let me know if you need any more help.
> 
> Cheers

Link dead!

**Comment by linnett** [comment]
@peyman-mohamadpour  thanks but this was 5 and a half years ago 😂😂😂
