### ISSUE TITLE
There was a problem generating our critical path CSS. Check your URL, or try again later.

### ISSUE THREAD

**Issue by Volnus** [pocketjoso/penthouse#62]
Whenever I try to check my CSS I keep getting that error. Now I thought it was a CSS issue HOWEVER when checking the console... 

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT  http://178.62.5.185/process.php

Any suggestions?

**Comment by pocketjoso** [comment]
Thanks for reporting. My `do` droplet ran out of memory, restarting now. Will be working again in ~10 min.

**Comment by pocketjoso** [comment]
Also this issue doesn't relate to `Penthouse`, so closing.

**Comment by Volnus** [comment]
I am so sorry for opening it up here lol

**Comment by pocketjoso** [comment]
@Volnus Don't worry about that - thanks again for alerting me! I'm going to make it more straight forward to report problems with the online tool from the page itself.
