### ISSUE TITLE
Strip out unused media queries

### ISSUE THREAD

**Issue by pocketjoso** [pocketjoso/penthouse#67]
Larger than the defined viewport.

**Comment by pocketjoso** [comment]
Rather then writing more custom CSS parsing functionality into `Penthouse` to be able to parse and remove certain media queries, I'm going to let this issue wait until we drop standalone command line support. I will then make use of [parse-css](https://www.npmjs.com/package/css-parse)s AST which will make custom media query removal super easy. Next step will be to let the penthouse core work on an AST object, rather than a CSS string.

cc @fatso83

**Comment by fatso83** [comment]
Cool ! Hoping to get started on this in two weeks. Any idea how we can
communicate with the Penthouse process from Node, sockets perhaps? I just
assume trying to use stdin/stdout and pipes for bidirectional communication
might prove awkward, handling errors and all, but I might be wrong :-) I
can imagine a possible solution, but hoping for a better foundation.

**Comment by pocketjoso** [comment]
Awesome - let's move that discussion to #68.

**Comment by pocketjoso** [comment]
Should be solve now.
