### ISSUE TITLE
error generating critical path

### ISSUE THREAD

**Issue by onelfri1617** [pocketjoso/penthouse#72]
My page is: http://onelfri.com

I want to inline:

http://onelfri.com/wp-content/cache/autoptimize/css/autoptimize_72a51b05e43d44f4a1fd32e05a6481cc.css

It is more than 800,000 characters, but I have selected only one part and there's always an error.  Not sure how to proceed.  Let me know if you can have the possibility of running more than 800K because I think it will not work otherwise.  

Also, does this work with external css?

**Comment by pocketjoso** [comment]
Hi,
I think the problem was just that the online generator was overloaded; it was giving a lot more errors than normal. I just ran your css split in half on the tool and it worked perfectly. Please try again.

Please note that in order to get the benefits of using critical css, you must:
* Also include the css for your fonts - all css from all `<style>` and `<link rel='stylesheet'>` tags on your page
* Move all your `<script>` tags out of the head of the document, and place them just before the closing `</body>` tag.

**Comment by pocketjoso** [comment]
@onelfri1617 Did that solve your problem?

**Comment by onelfri1617** [comment]
Hey, yea I was able to use the generator but, when I got the critical path css code and updated autoptimize to inline above the fold with it it broke my footer and my google page speed grade went down.  Not sure why this is...  could be because the css file is from autoptimize (see above)

**Comment by pocketjoso** [comment]
@onelfri1617 Did you include all the css from your page like I said? 

 > it broke my footer 
Do you mean that it looked broken (missing styles), or that it stopped working in terms of (javascript) interaction?

**Comment by onelfri1617** [comment]
The footer looked broken.  Also, page speed grade from google went down a lot. Sent from Yahoo Mail for iPadOn Aug 21, 2015, 2:39:14 AM, Jonas Ohlsson wrote:@onelfri1617 Did you include all the css from your page like I said? 


it broke my footer 
Do you mean that it looked broken (missing styles), or that it stopped working in terms of (javascript) interaction?

**Comment by pocketjoso** [comment]
The critical css would most likely not include the footer; the point is to only include what's seen in the viewport during load of the page. You footer's CSS should load with your full CSS, which you should load at the end of the page, before the `</body>` tag.

**Comment by pocketjoso** [comment]
Closing as the problem(s) don't seem to relate to `Penthouse`. @onelfri1617 feel free to re-open and comment if you still have issues.
