### ISSUE TITLE
Specifying output file when using as a node_module

### ISSUE THREAD

**Issue by computapars** [pocketjoso/penthouse#74]
Is there a way to specify an output file when using Penthouse as a node module? Looks like all the options I can pass in when invoking penthouse won't allow this.

**Comment by pocketjoso** [comment]
Hi,
You're right, there's no direct option to specify an outfile, but all you need to do is to take the css returned in the success function and write it to file:
```
penthouse({
    url : 'http://google.com',
    css : path.join(__basedir + 'static/main.css')
}, function(err, criticalCss) {
  if (err) { // handle error }
  fs.writeFileSync('myCriticalCss.css', criticalCss);
});
```

**Comment by fatso83** [comment]
Maybe we should add that to the README, as newcomers to Node programming might not be too familiar with the file operations

**Comment by pocketjoso** [comment]
> Maybe we should add that to the README, as newcomers to Node programming might not be too familiar with the file operations

[Done.](https://github.com/pocketjoso/penthouse/commit/53984aa423a30581142b6cfc19c3d694ba0dc49e)

--

Closing this for now, @computapars please feel free to reopen and clarify if you had more questions or something else in mind!

**Comment by computapars** [comment]
Thank you. That is very helpful!
