### ISSUE TITLE
Multiple CSS parameters?

### ISSUE THREAD

**Issue by relhtml** [pocketjoso/penthouse#75]
Thanks for creating and maintaining this project. I was just curious if Penthouse supports multiple CSS files as an input?

As an example, I have 2 external CSS files on a page, but I can't bundle them for reasons involving IE8 file size limitations on those types of files. Ideally, penthouse would allow for the following optional parameters: 

    phantomjs penthouse.js http://mySite.com/page1 bundle1.css bundle2.css > page1-critical-styles.css

Is this possible?

Thanks

**Comment by pocketjoso** [comment]
Well `penthouse` is not IE8 - why would you not be able to bundle them together just for `penthouse`?

**Comment by fatso83** [comment]
I don't get this either. @relhtml: the critical css produced by bunding the css together will be much smaller than any of the two files you input. 

I'd just do this:
```
cat bundle1.css bundle2.css > bundle.css
phantomjs penthouse.js http://mySite.com/page1 bundled.css > page1-critical-styles.css
```

Your proposed change is simply delegating the concatenation to penthouse, which really is out of scope. Closing. Feel free to comment if you disagree in some way.
