### ISSUE TITLE
:hover isn't working

### ISSUE THREAD

**Issue by Znegl** [pocketjoso/penthouse#79]
I'm trying generate critical CSS for a site, but because the main navigation is based on :hover it doesn't work until the rest of the CSS is loaded.
Would it be possible to include :hover style as an optional parameter?

**Comment by pocketjoso** [comment]
`:hover` styles do not belong in critical css (hence why Penthouse removes them). My general advice would be to make sure your full css doesn't take ages to load and go down that route.

.. if you're in a situation where your site appears really broken without the hover effect, the best solution I can offer right now is:
* use javascript to hide/disable the element that has the hover effect until the full css has loaded, only then turn it back to normal. To get a callback for the full css load you can use [loadCss](https://github.com/filamentgroup/loadCSS) (which also speeds up full css loads marginally)

`Penthouse` will have a `forceInclude` option in the future which will allow you to force include your `<mySelector>:hover` styles, but it's not ready yet.

**Comment by Znegl** [comment]
Thanks for the quick reply! Actually we're depending on a pure CSS solution to not be dependend on JS in our primary navigation, so i guess we'll just be waiting for the forceInclude feature :)

Great project!

**Comment by pocketjoso** [comment]
Cheers, glad you like it! :)
