### ISSUE TITLE
Add to the critical css all the rules from different media queries

### ISSUE THREAD

**Issue by greenido** [pocketjoso/penthouse#83]
I've tried the tool and got a lower score in PSI after taking the critical CSS because it was missing all the rules for mobile/tablet.
It would be great to include all of them as default.

Thanks!

**Comment by pocketjoso** [comment]
Hi @greenido. `Penthouse` does keep styles for all media queries, as long as the elements the styles apply to are within the critical viewport (which is almost always the case when doing mobile first). If they're missing for you, then something (else) is going wrong.

What version of `Penthouse` do you have installed? [0.4.0](https://github.com/pocketjoso/penthouse/releases/tag/v.0.4.0) made `Penthouse` very intolerant to css errors, so if you're using >= 0.4.0 I recommend that you first validate your css and fix any errors. The parse Penthouse currently uses has an online UI here: http://iamdustan.com/reworkcss_ast_explorer/.

**Comment by greenido** [comment]
Ahh!
I've just tried the online version here:
https://jonassebastianohlsson.com/criticalpathcssgenerator/
But let me check again my CSS... It's mostly bootstrap 3 with some more
rules.

**Comment by pocketjoso** [comment]
The online version still uses an older version of penthouse `0.3.4`, so what I said about invalid css is less relevant.

Can you share the url you're having problems with?

**Comment by greenido** [comment]
Sure.
It my project site: Ido-green.appspot.com


--from my mobile

**Comment by pocketjoso** [comment]
Hmm. It seems to work correctly for me when I generate the critical css using the latest version of Penthouse:

https://gist.github.com/pocketjoso/b4653a78df8de24c51c9

If you can confirm that this is correct I will go and update the version used for the online generator.

**Comment by greenido** [comment]
Perfect!!
Thank you very much!
