### ISSUE TITLE
PhantomJs process exited with code null

### ISSUE THREAD

**Issue by crobinson42** [pocketjoso/penthouse#93]
Here's my code using critical css module
```
critical.generate({
      base: tmpDir,
      html: html,
      css : [params.cssMap.path],
      width: params.width || 1000,
      height: params.height || 2000,
      minify: true
  }).then(function (output) {
    // You now have critical-path CSS
    // Works with and without dest specified
    console.log('output',output)
}).error(function (err) {
    console.log('err',err);
});
```

here's my console log:
```
err { [Error]
  cause: 
   { [Error]
     code: null,
     debug: 'PhantomJS process exited with code null',
     stdout: '',
     stderr: '' },
  isOperational: true,
  code: null,
  debug: 'PhantomJS process exited with code null',
  stdout: '',
  stderr: '' }
```

**Comment by pocketjoso** [comment]
Hi there,
Can you provide more context? What version of `penthouse` (you might have to look that up via your `critical` version)? Could you share the `html` and `css` you used? If not, please try some other ways to reduce your test case - f.e. does it work if you change the css to `''`? or if you pass in a blank skeleton `html`?

**Comment by crobinson42** [comment]
Thx for the quick response, will try now and update shortly.

**Comment by crobinson42** [comment]
Penthouse is v0.3.6 - I can't post the html/css, company policy.
I tried passing in blank html w/ body tags as the html as well as clearing out the css file then passing ' ' as the css path and I get an error that says it cannot open that path... 

The weird thing is this was all working and almost to prod when the dependencies broke with phantomjs?!

**Comment by pocketjoso** [comment]
That's weird - you're saying you get the same error with an empty template? Almost sounds like an issue with the `critical` package then, I can't quite imagine what would cause penthouse errors if the html and css is blank...

What `os` are you running?

**Comment by pocketjoso** [comment]
What version of `critical` are you on?

**Comment by crobinson42** [comment]
critical is v0.6.0 and i'm on mac

**Comment by pocketjoso** [comment]
You should be on `penthouse@^0.7.0` if you're on [critical v0.6.0](https://github.com/addyosmani/critical/blob/master/package.json#L47).. wonder if you're node module dependencies have gone bad.. most likely not - but I guess try to remove and re-install at least the `critical` package.

If that doesn't work, given what you said here:
> I tried passing in blank html w/ body tags as the html as well as clearing out the css file then passing ' ' as the css path and I get an error that says it cannot open that path...

..I would direct you to `critical` and open an issue there, if you can't even run with some simple sane input. Not much else I can do without any more specific error causing input. :/

**Comment by pocketjoso** [comment]
@crobinson42 any news on this?

**Comment by crobinson42** [comment]
Yeah it was mom issues on the machine, everything deployed fine

**Comment by pocketjoso** [comment]
Sweet.

**Comment by mattgreenfield** [comment]
I was having the same issue, updating Penthouse to the latest version with npm fixed it.

**Comment by mbrevda** [comment]
With 0.10.4 on OS X, Im having this issue, too (also via critical)

**Comment by pocketjoso** [comment]
@mbrevda https://github.com/pocketjoso/penthouse/issues/93#issuecomment-161095426 - thanks!
